# Raw questions for bo01
import json
from normalizer import normalize_question

raw_questions = [
  {"id": "bo01-q001", "number": 1, "type": "multiple_choice", "question": "“Look ...” has similar meaning to “take care”. A. up B. at C. in D. after", "options": ["up", "at", "in", "after"], "answer": "after", "audio": None},
  {"id": "bo01-q002", "number": 2, "type": "fill_blank", "question": "Her father is going to have tea and read the _ _ _ _ _ _ _ _ _ .", "answer": "newspaper", "audio": None},
  {"id": "bo01-q003", "number": 3, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["My friend is staying with us next week.", "My uncle is staying with us this week.", "My aunt is staying with us this week.", "My aunt is staying with us next week."], "answer": "My aunt is staying with us this week.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302352490500592_Audio.mp3"},
  {"id": "bo01-q004", "number": 4, "type": "multiple_choice", "question": "Which sentence is incorrect?", "options": ["She helps me to choose a shirt.", "Your explanation helps me to understand the problem.", "Thank for help me cleaning the car.", "Let me help you."], "answer": "Thank for help me cleaning the car.", "audio": None},
  {"id": "bo01-q005", "number": 5, "type": "multiple_choice", "question": "She added a little soy sauce ... the dish.", "options": ["of", "up", "to", "with"], "answer": "to", "audio": None},
  {"id": "bo01-q006", "number": 6, "type": "fill_blank", "question": "Jane and Jack stood in _ _ _ _ _ of the mirror and looked at themselves.", "answer": "front", "audio": None},
  {"id": "bo01-q007", "number": 7, "type": "image_fill", "question": "Lan: Why didn’t you come to Nam’s b_ _ _ _ _ _ _ party yesterday? - Quang: I had a headache.", "answer": "irthday", "audio": None},
  {"id": "bo01-q008", "number": 8, "type": "fill_blank", "question": "Let’s put the coffee table in the middle _ _ the room.", "answer": "of", "audio": None},
  {"id": "bo01-q009", "number": 9, "type": "fill_blank", "question": "What are you doing, Nam? - I’m _ _ _ _ _ _ _ a letter from Tony.", "answer": "reading", "audio": None},
  {"id": "bo01-q010", "number": 10, "type": "multiple_choice", "question": "Can you give me … meat?", "options": ["a", "an", "some", "few"], "answer": "some", "audio": None},
  {"id": "bo01-q011", "number": 11, "type": "fill_blank", "question": "The doctor told me to stop thinking and then took some exercises. I felt relaxing _ _ _ _ _ _ ard.", "answer": "afterw", "audio": None},
  {"id": "bo01-q012", "number": 12, "type": "word_order", "question": "happy to/ They/ activities./ are very/ join our winter/", "answer": "They are very happy to join our winter activities.", "audio": None},
  {"id": "bo01-q013", "number": 13, "type": "fill_blank", "question": "Jane is a friend _ _ mine.", "answer": "of", "audio": None},
  {"id": "bo01-q014", "number": 14, "type": "word_order", "question": "going to/ are/ When/ you/ get married?/", "answer": "When are you going to get married?", "audio": None},
  {"id": "bo01-q015", "number": 15, "type": "fill_blank", "question": "APP_ IANCE", "answer": "L", "audio": None},
  {"id": "bo01-q016", "number": 16, "type": "multiple_choice", "question": "A ... can fix your tooth.", "options": ["dentist", "mechanic", "author", "engineer"], "answer": "dentist", "audio": None},
  {"id": "bo01-q017", "number": 17, "type": "multiple_choice", "question": "How much does it … to mail a local letter in Vietnam?", "options": ["take", "pay", "require", "cost"], "answer": "cost", "audio": None},
  {"id": "bo01-q018", "number": 18, "type": "multiple_choice", "question": "Every day the doctor has to … surgery on different patients.", "options": ["operate", "create", "perform", "cause"], "answer": "perform", "audio": None},
  {"id": "bo01-q019", "number": 19, "type": "fill_blank", "question": "SNEE_ E", "answer": "Z", "audio": None},
  {"id": "bo01-q020", "number": 20, "type": "fill_blank", "question": "His father bou_ _ _ him a new schoolbag yesterday.", "answer": "ght", "audio": None},
  {"id": "bo01-q021", "number": 21, "type": "fill_blank", "question": "My sister doesn’t play tennis as well as she _ _ _ last year.", "answer": "did", "audio": None},
  {"id": "bo01-q022", "number": 22, "type": "multiple_choice", "question": "The nurse will ... your height again.", "options": ["weigh", "take", "measure", "do"], "answer": "measure", "audio": None},
  {"id": "bo01-q023", "number": 23, "type": "word_order", "question": "There/ aren’t/ this one./ any buses/ after/", "answer": "There aren’t any buses after this one.", "audio": None},
  {"id": "bo01-q024", "number": 24, "type": "fill_blank", "question": "He often goes out _ _ _ a walk in summer nights.", "answer": "for", "audio": None},
  {"id": "bo01-q025", "number": 25, "type": "multiple_choice", "question": "Mary … in the dance sport club since last year.", "options": ["participates", "participated", "has participated", "is participating"], "answer": "has participated", "audio": None},
  {"id": "bo01-q026", "number": 26, "type": "word_order", "question": "are on/ to/ English books/ the right./ the shelf/", "answer": "English books are on the shelf to the right.", "audio": None},
  {"id": "bo01-q027", "number": 27, "type": "word_order", "question": "April/ is/ 2015./ Today/ 11th of/", "answer": "Today is 11th of April 2015.", "audio": None},
  {"id": "bo01-q028", "number": 28, "type": "word_order", "question": "exams/ yesterday./ Four of us/ had/ important/", "answer": "Four of us had important exams yesterday.", "audio": None},
  {"id": "bo01-q029", "number": 29, "type": "fill_blank", "question": "The scientists in the world are _ _ _ _ _ research on AIDS.", "answer": "doing", "audio": None},
  {"id": "bo01-q030", "number": 30, "type": "fill_blank", "question": "Did you play volleyball _ _ _ _ week? – No, I didn’t.", "answer": "last", "audio": None},
  {"id": "bo01-q031", "number": 31, "type": "image_fill", "question": "She lives in a house with a lot of _ _ _ _ _ _ _ in front of it.", "answer": "flowers", "audio": None},
  {"id": "bo01-q032", "number": 32, "type": "fill_blank", "question": "Mr. Ronald is very strong. He’s a weightlif_ _ _ .", "answer": "ter", "audio": None},
  {"id": "bo01-q033", "number": 33, "type": "word_order", "question": "going/ Are you/ abroad for/ your vacation/ next year?/", "answer": "Are you going abroad for your vacation next year?", "audio": None},
  {"id": "bo01-q034", "number": 34, "type": "word_order", "question": "all evening./ TV/ My sisters/ just sit/ and watch/", "answer": "My sisters just sit and watch TV all evening.", "audio": None},
  {"id": "bo01-q035", "number": 35, "type": "word_order", "question": "try to/ Our teachers/ full potential./ help us/ realize our/", "answer": "Our teachers try to help us realize our full potential.", "audio": None},
  {"id": "bo01-q036", "number": 36, "type": "fill_blank", "question": "Finally, I’m going to fly home _ _ _ _ lots of Vietnamese souvenirs.", "answer": "with", "audio": None},
  {"id": "bo01-q037", "number": 37, "type": "word_order", "question": "by plane?/ travel/ to/ interesting/ Is it/", "answer": "Is it interesting to travel by plane?", "audio": None},
  {"id": "bo01-q038", "number": 38, "type": "multiple_choice", "question": "When’s your birthday?", "options": ["6.50", "June 6th", "June and 6", "a June 6"], "answer": "June 6th", "audio": None},
  {"id": "bo01-q039", "number": 39, "type": "word_order", "question": "eat too/ much before/ you go/ You shouldn’t/ to bed./", "answer": "You shouldn’t eat too much before you go to bed.", "audio": None},
  {"id": "bo01-q040", "number": 40, "type": "fill_blank", "question": "Nga is talking to her friend n_ _ .", "answer": "ow", "audio": None},
  {"id": "bo01-q041", "number": 41, "type": "fill_blank", "question": "The city has a popu_ _ _ _ _ _ of 2.6 million", "answer": "lation", "audio": None},
  {"id": "bo01-q042", "number": 42, "type": "listening_fill", "question": "I just work day by day to _ _ _ _ _ my bad habits.", "answer": "break", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/2/23/636865180515796394_Audio.mp3"},
  {"id": "bo01-q043", "number": 43, "type": "fill_blank", "question": "MEC_ ANIC", "answer": "H", "audio": None},
  {"id": "bo01-q044", "number": 44, "type": "word_order", "question": "Tomorrow/ birthday./ Jennifer’s/ will be/ 9th/", "answer": "Tomorrow will be Jennifer’s 9th birthday.", "audio": None},
  {"id": "bo01-q045", "number": 45, "type": "fill_blank", "question": "Is he interested in collecting old _ _ _ _ _ _ and coins?", "answer": "stamps", "audio": None},
  {"id": "bo01-q046", "number": 46, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["nose", "coffee", "soda", "potato"], "answer": "coffee", "audio": None},
  {"id": "bo01-q047", "number": 47, "type": "fill_blank", "question": "COMMO_", "answer": "N", "audio": None},
  {"id": "bo01-q048", "number": 48, "type": "fill_blank", "question": "M_ DICINE", "answer": "E", "audio": None},
  {"id": "bo01-q049", "number": 49, "type": "multiple_choice", "question": "In the class, nobody’s eaten Chinese food and … I.", "options": ["so am", "neither am", "neither do", "neither have"], "answer": "neither have", "audio": None},
  {"id": "bo01-q050", "number": 50, "type": "multiple_choice", "question": "Bill ... his bike to school everyday.", "options": ["runs", "travels", "rides", "drives"], "answer": "rides", "audio": None},
  {"id": "bo01-q051", "number": 51, "type": "fill_blank", "question": "M_ NUTE", "answer": "I", "audio": None},
  {"id": "bo01-q052", "number": 52, "type": "fill_blank", "question": "My aunt has two children, one boy and one _ _ _ _ .", "answer": "girl", "audio": None},
  {"id": "bo01-q053", "number": 53, "type": "multiple_choice", "question": "He has a garage. The garage is ….", "options": ["him", "of him", "his", "of his"], "answer": "his", "audio": None},
  {"id": "bo01-q054", "number": 54, "type": "word_order", "question": "regularly./ and I/ each other/ My friend/ write to/", "answer": "My friend and I write to each other regularly.", "audio": None},
  {"id": "bo01-q055", "number": 55, "type": "word_order", "question": "This is/ with/ her cat./ a photo of/ my sister/", "answer": "This is a photo of my sister with her cat.", "audio": None},
  {"id": "bo01-q056", "number": 56, "type": "multiple_choice", "question": "Last year I … on a home-stay to the United States.", "options": ["go", "goes", "went", "gone"], "answer": "went", "audio": None},
  {"id": "bo01-q057", "number": 57, "type": "multiple_choice", "question": "I often ... my friends in front of the school gate.", "options": ["say", "talk", "speak", "meet"], "answer": "meet", "audio": None},
  {"id": "bo01-q058", "number": 58, "type": "fill_blank", "question": "We often have a _ _ _ _ _ _ when the weather is fine.", "answer": "picnic", "audio": None},
  {"id": "bo01-q059", "number": 59, "type": "word_order", "question": "an hour/ spends half/ cooking/ My mother/ lunch./", "answer": "My mother spends half an hour cooking lunch.", "audio": None},
  {"id": "bo01-q060", "number": 60, "type": "listening_multiple_choice", "question": "What does he like? - ....", "options": ["Spending time with her family", "Spending time with her friend", "Spending time on his homework", "Spending time on facebook"], "answer": "Spending time with her family", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/3/6/635612601878637771_Audio.mp3"},
  {"id": "bo01-q061", "number": 61, "type": "word_order", "question": "Which/ fruits/ or bananas?/ would you/ like, apples/", "answer": "Which fruits would you like, apples or bananas?", "audio": None},
  {"id": "bo01-q062", "number": 62, "type": "multiple_choice", "question": "Please don’t … so much noise.", "options": ["go", "make", "do", "take"], "answer": "make", "audio": None},
  {"id": "bo01-q063", "number": 63, "type": "fill_blank", "question": "Do you enjoy _ _ _ _ _ given gifts by the others on your birthday?", "answer": "being", "audio": None},
  {"id": "bo01-q064", "number": 64, "type": "image_fill", "question": "Most people know that coffee makes it difficult to go to _ _ _ _ _ .", "answer": "sleep", "audio": None},
  {"id": "bo01-q065", "number": 65, "type": "stress", "question": "Choose the word which has different stress pattern:", "options": ["unhappy", "comfortable", "expensive", "material"], "answer": "comfortable", "audio": None},
  {"id": "bo01-q066", "number": 66, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently from the others:", "options": ["naked", "sacred", "wanted", "walked"], "answer": "walked", "audio": None},
  {"id": "bo01-q067", "number": 67, "type": "image_fill", "question": "My sister plays flute in our school _ _ _ _ _ _ tra.", "answer": "orches", "audio": None},
  {"id": "bo01-q068", "number": 68, "type": "fill_blank", "question": "PLEAS_ NT", "answer": "A", "audio": None},
  {"id": "bo01-q069", "number": 69, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["temple", "help", "market", "hotel"], "answer": "market", "audio": None},
  {"id": "bo01-q070", "number": 70, "type": "stress", "question": "The word “destination” has ... syllables.", "options": ["three", "five", "four", "none are correct"], "answer": "four", "audio": None},
  {"id": "bo01-q071", "number": 71, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["buffalo", "pull", "struture", "uncle"], "answer": "pull", "audio": None},
  {"id": "bo01-q072", "number": 72, "type": "multiple_choice", "question": "In Vietnam, students … to wear uniforms at school.", "options": ["want", "have", "ought", "need"], "answer": "have", "audio": None},
  {"id": "bo01-q073", "number": 73, "type": "multiple_choice", "question": "Please drop … for a cup of coffee whenever you are passing.", "options": ["down", "in", "off", "on"], "answer": "in", "audio": None},
  {"id": "bo01-q074", "number": 74, "type": "fill_blank", "question": "Everybody is waiting _ _ _ the president in the hall now.", "answer": "for", "audio": None},
  {"id": "bo01-q075", "number": 75, "type": "fill_blank", "question": "We usually _ _ _ _ a picnic when we have free time.", "answer": "have", "audio": None},
  {"id": "bo01-q076", "number": 76, "type": "multiple_choice", "question": "How often do you jog? – ....", "options": ["Three times a week", "Third time a week", "Third times a week", "Three time a week"], "answer": "Three times a week", "audio": None},
  {"id": "bo01-q077", "number": 77, "type": "fill_blank", "question": "Where _ _ _ _ you yesterday evening? I didn’t see you.", "answer": "were", "audio": None},
  {"id": "bo01-q078", "number": 78, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["Today I go to the library and borrow some story books.", "Today I go to the library and chose some scary books.", "Today I go to the library and choose some story books.", "Today I goes to the library and chooses some story books."], "answer": "Today I go to the library and choose some story books.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/29/635213183821850444_Audio.mp3"},
  {"id": "bo01-q079", "number": 79, "type": "multiple_choice", "question": "My new glasses cost me … the last pair that I bought.", "options": ["three times as much as", "as much three times as", "three times more", "times three"], "answer": "three times as much as", "audio": None},
  {"id": "bo01-q080", "number": 80, "type": "multiple_choice", "question": "I tried … to him but he still misunderstood.", "options": ["explain", "to explain", "explaining", "explained"], "answer": "to explain", "audio": None},
  {"id": "bo01-q081", "number": 81, "type": "word_order", "question": "new to/ something/ that I have/ I remember/ tell you./", "answer": "I remember that I have something new to tell you.", "audio": None},
  {"id": "bo01-q082", "number": 82, "type": "listening_fill", "question": "I was so tired, so I had a glass of _ _ _ _ _ _ _ _ .", "answer": "lemonade", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241436304616058_Audio.mp3"},
  {"id": "bo01-q083", "number": 83, "type": "fill_blank", "question": "Keep _ _ _ _ _ _ , please. Our teacher is explaining the lesson.", "answer": "silent", "audio": None},
  {"id": "bo01-q084", "number": 84, "type": "word_order", "question": "studies/ school./ in the/ She always/ library after/", "answer": "She always studies in the library after school.", "audio": None},
  {"id": "bo01-q085", "number": 85, "type": "multiple_choice", "question": "Oh, I don’t like pork. - ....", "options": ["I don’t like, too", "Either do I", "Neither do I", "So don’t I"], "answer": "Neither do I", "audio": None},
  {"id": "bo01-q086", "number": 86, "type": "listening_multiple_choice", "question": "What doesn’t he have? - ....", "options": ["A tennis racquet", "A table tennis table", "A tennis paddle", "A table tennis paddle"], "answer": "A table tennis paddle", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302347187739278_Audio.mp3"},
  {"id": "bo01-q087", "number": 87, "type": "word_order", "question": "on the tree?/ Are/ any/ birds/ there/", "answer": "Are there any birds on the tree?", "audio": None},
  {"id": "bo01-q088", "number": 88, "type": "multiple_choice", "question": "Peter sometimes helps me … my homework.", "options": ["to do", "do", "with", "All are correct"], "answer": "All are correct", "audio": None},
  {"id": "bo01-q089", "number": 89, "type": "listening_multiple_choice", "question": "What did the man save some money for?", "options": ["to buy the television", "to travel around the world", "to buy the new house", "to travel around Europe"], "answer": "to buy the television", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/12/8/636168090746217437_Audio.mp3"},
  {"id": "bo01-q090", "number": 90, "type": "fill_blank", "question": "Could you give me some cookies? - _ _ _ _ you are.", "answer": "here", "audio": None},
  {"id": "bo01-q091", "number": 91, "type": "listening_multiple_choice", "question": "What could man do after the invention of breathing equipment? - ....", "options": ["Man could breathe freely underwater", "Man could swim freely undersea", "Man could swim freely underwater", "Man could breathe freely in the swimming pool"], "answer": "Man could swim freely underwater", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302333504175244_Audio.mp3"},
  {"id": "bo01-q092", "number": 92, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["There were many sharks, dolphins and turtles.", "There weren’t many sharks, dolphins and turtles.", "There were some sharks, dolphins and turtles.", "There were sometimes many sharks, dolphins and turtles."], "answer": "There were many sharks, dolphins and turtles.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302360873643316_Audio.mp3"},
  {"id": "bo01-q093", "number": 93, "type": "word_order", "question": "in a/ days a/ factory five/ week./ Mr. John works/", "answer": "Mr. John works in a factory five days a week.", "audio": None},
  {"id": "bo01-q094", "number": 94, "type": "multiple_choice", "question": "The medicines ... the symptoms of the common cold.", "options": ["relieve", "disappear", "catch", "prevents"], "answer": "relieve", "audio": None},
  {"id": "bo01-q095", "number": 95, "type": "word_order", "question": "bus near my/ walk from the/ I catch the/ bus stop to school./ house and then/", "answer": "I catch the bus near my house and then walk from the bus stop to school.", "audio": None},
  {"id": "bo01-q096", "number": 96, "type": "word_order", "question": "called Peter/ left a message/ for you/ A man/ at the hotel./", "answer": "A man called Peter left a message for you at the hotel.", "audio": None},
  {"id": "bo01-q097", "number": 97, "type": "multiple_choice", "question": "We bought ... as souvenirs for our parents.", "options": ["all kinds of stamp", "all kind of stamp", "all kind of stamps", "all kinds of stamps"], "answer": "all kinds of stamps", "audio": None},
  {"id": "bo01-q098", "number": 98, "type": "fill_blank", "question": "Goodbye! – Bye, _ _ _ you later.", "answer": "see", "audio": None},
  {"id": "bo01-q099", "number": 99, "type": "fill_blank", "question": "How often do you _ _ _ _ _ your room?", "answer": "clean", "audio": None},
  {"id": "bo01-q100", "number": 100, "type": "word_order", "question": "two hours/ to do/ It takes her/ each day/ her homework./", "answer": "It takes her two hours each day to do her homework.", "audio": None},
  {"id": "bo01-q101", "number": 101, "type": "fill_blank", "question": "She bought some souvenirs _ _ _ _ the shop and so did I.", "answer": "from", "audio": None},
  {"id": "bo01-q102", "number": 102, "type": "fill_blank", "question": "CA_ CH", "answer": "T", "audio": None},
  {"id": "bo01-q103", "number": 103, "type": "fill_blank", "question": "Please prepare, I will p_ _ _ you up at 8 a.m.", "answer": "ick", "audio": None},
  {"id": "bo01-q104", "number": 104, "type": "word_order", "question": "Jackson’s brother is/ Ho Chi Minh city/ going to/ by plane,/ not by car./", "answer": "Jackson’s brother is going to Ho Chi Minh city by plane, not by car.", "audio": None},
  {"id": "bo01-q105", "number": 105, "type": "fill_blank", "question": "What _ _ _ _ do your family often go to bed everyday? – 11pm.", "answer": "time", "audio": None},
  {"id": "bo01-q106", "number": 106, "type": "word_order", "question": "He drinks/ of mineral/ water/ a lot/ a day./", "answer": "He drinks a lot of mineral water a day.", "audio": None},
  {"id": "bo01-q107", "number": 107, "type": "word_order", "question": "people/ enough/ there/ in this meeting?/ Are/", "answer": "Are there enough people in this meeting?", "audio": None},
  {"id": "bo01-q108", "number": 108, "type": "fill_blank", "question": "When it becomes hot, people often feel th_ _ _ _ _ .", "answer": "irsty", "audio": None},
  {"id": "bo01-q109", "number": 109, "type": "word_order", "question": "is the/ This book/ most/ interesting/ of the three./", "answer": "This book is the most interesting of the three.", "audio": None},
  {"id": "bo01-q110", "number": 110, "type": "fill_blank", "question": "Mr. Pike often takes his sons to the _ _ _ to see wild animals.", "answer": "zoo", "audio": None},
  {"id": "bo01-q111", "number": 111, "type": "fill_blank", "question": "MEAS_ RE", "answer": "U", "audio": None},
  {"id": "bo01-q112", "number": 112, "type": "fill_blank", "question": "He talks a _ _ _ about his new car.", "answer": "lot", "audio": None},
  {"id": "bo01-q113", "number": 113, "type": "multiple_choice", "question": "She has a … ruler.", "options": ["white long", "white to long", "long white", "None are correct"], "answer": "long white", "audio": None},
  {"id": "bo01-q114", "number": 114, "type": "fill_blank", "question": "Don’t worry about _ _ , Mom. I can take care of myself.", "answer": "me", "audio": None},
  {"id": "bo01-q115", "number": 115, "type": "fill_blank", "question": "PLEAS_ D", "answer": "E", "audio": None},
  {"id": "bo01-q116", "number": 116, "type": "word_order", "question": "sister have/ than you?/ more or/ Does your/ fewer vacations/", "answer": "Does your sister have more or fewer vacations than you?", "audio": None},
  {"id": "bo01-q117", "number": 117, "type": "listening_fill", "question": "I thought that he might like some candy but my father really doesn’t eat many _ _ _ _ _ _ .", "answer": "sweets", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241555798443549_Audio.mp3"},
  {"id": "bo01-q118", "number": 118, "type": "multiple_choice", "question": "Life on the farm is always a struggle … nature.", "options": ["with", "on", "for", "a long"], "answer": "with", "audio": None},
  {"id": "bo01-q119", "number": 119, "type": "word_order", "question": "Unlike the/ actions./ more/ novels,/ films show/", "answer": "Unlike the novels, films show more actions.", "audio": None},
  {"id": "bo01-q120", "number": 120, "type": "multiple_choice", "question": "Many wild animals are ... danger because of pollution.", "options": ["to", "for", "at", "in"], "answer": "in", "audio": None},
  {"id": "bo01-q121", "number": 121, "type": "multiple_choice", "question": "Could you tell me … to get to the post office?", "options": ["how", "what way", "what direction", "in what way"], "answer": "how", "audio": None},
  {"id": "bo01-q122", "number": 122, "type": "listening_fill", "question": "As we were _ _ _ _ _ _ _ _ the street, we saw an accident.", "answer": "crossing", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/1/9/635563935835834218_Audio.mp3"},
  {"id": "bo01-q123", "number": 123, "type": "listening_multiple_choice", "question": "What kind of men does she like? - ....", "options": ["Intelligent and funny men", "Silent and sleepy men", "Intelligent and tidy men", "Violent and manly men"], "answer": "Intelligent and funny men", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302339943242554_Audio.mp3"},
  {"id": "bo01-q124", "number": 124, "type": "fill_blank", "question": "Did you _ _ _ _ the flu last week? – Yes, I did.", "answer": "have", "audio": None},
  {"id": "bo01-q125", "number": 125, "type": "listening_fill", "question": "I have a sore throat and _ _ _ _ _ nose.", "answer": "runny", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2019-2020/Tinh_Thanhpho/L7/nghe/de1/9.mp3"},
  {"id": "bo01-q126", "number": 126, "type": "word_order", "question": "friends again./ They’re/ forward to/ looking/ meeting old/", "answer": "They’re looking forward to meeting old friends again.", "audio": None},
  {"id": "bo01-q127", "number": 127, "type": "multiple_choice", "question": "In Britain school always … in September.", "options": ["behin", "begins", "began", "beginning"], "answer": "begins", "audio": None},
  {"id": "bo01-q128", "number": 128, "type": "fill_blank", "question": "People _ _ all ages can enjoy sport activities.", "answer": "of", "audio": None},
  {"id": "bo01-q129", "number": 129, "type": "word_order", "question": "began/ forest./ to race/ in the/ They/", "answer": "They began to race in the forest.", "audio": None},
  {"id": "bo01-q130", "number": 130, "type": "image_fill", "question": "Have you got a headache and _ _ _ _ _ _ _ _ ?", "answer": "backache", "audio": None},
  {"id": "bo01-q131", "number": 131, "type": "word_order", "question": "How much/ at birth?/ does a/ baby elephant/ weigh/", "answer": "How much does a baby elephant weigh at birth?", "audio": None},
  {"id": "bo01-q132", "number": 132, "type": "word_order", "question": "ask him/ me back?/ to/ Could you/ call/", "answer": "Could you ask him to call me back?", "audio": None},
  {"id": "bo01-q133", "number": 133, "type": "word_order", "question": "children./ on the beach/ three/ with their/ They were/", "answer": "They were on the beach with their three children.", "audio": None},
  {"id": "bo01-q134", "number": 134, "type": "word_order", "question": "to check/ Remember/ numbers./ flight/ your/", "answer": "Remember to check your flight numbers.", "audio": None},
  {"id": "bo01-q135", "number": 135, "type": "word_order", "question": "I live in/ is/ The city/ very noisy/ at night./", "answer": "The city I live in is very noisy at night.", "audio": None},
  {"id": "bo01-q136", "number": 136, "type": "multiple_choice", "question": "It says on her report that she ... 40 kilos.", "options": ["is", "weigh", "weighs", "weight"], "answer": "weighs", "audio": None},
  {"id": "bo01-q137", "number": 137, "type": "image_fill", "question": "We ate a delicious dinner at a Mexican _ _ _ _ _ _ _ _ _ _ last Wednesday.", "answer": "restaurant", "audio": None},
  {"id": "bo01-q138", "number": 138, "type": "multiple_choice", "question": "They’re going to Hanoi this summer vacation. A “vacation” here is also a ....", "options": ["festival", "trip", "journey", "holiday"], "answer": "holiday", "audio": None},
  {"id": "bo01-q139", "number": 139, "type": "multiple_choice", "question": "What ... you do the last time you ... a bad toothache?", "options": ["do / had", "did / have", "did / had", "do / have"], "answer": "did / had", "audio": None},
  {"id": "bo01-q140", "number": 140, "type": "fill_blank", "question": "_ _ _ _ _ day of the week is the School’s festival day?", "answer": "which", "audio": None},
  {"id": "bo01-q141", "number": 141, "type": "multiple_choice", "question": "In big cities, an apartment is suitable ... small family.", "options": ["to", "of", "on", "for"], "answer": "for", "audio": None},
  {"id": "bo01-q142", "number": 142, "type": "multiple_choice", "question": "It’s nearly 5 pm. “Nearly” here is similar to ....", "options": ["beside", "before", "between", "almost"], "answer": "almost", "audio": None},
  {"id": "bo01-q143", "number": 143, "type": "fill_blank", "question": "How far is it _ _ _ _ here to your house?", "answer": "from", "audio": None},
  {"id": "bo01-q144", "number": 144, "type": "fill_blank", "question": "She looked at my teeth and told me _ _ _ to worry.", "answer": "not", "audio": None},
  {"id": "bo01-q145", "number": 145, "type": "word_order", "question": "often snows/ in winter./ country, it/ a lot/ In my/", "answer": "In my country, it often snows a lot in winter.", "audio": None},
  {"id": "bo01-q146", "number": 146, "type": "multiple_choice", "question": "Why does she speak English well? – Because she studies English very well.", "options": ["How does she speak English?", "Why does she speak English well?", "Why can’t she speak English well?", "How is she speaking English well?"], "answer": "Why does she speak English well?", "audio": None},
  {"id": "bo01-q147", "number": 147, "type": "stress", "question": "Choose the word which has different stress pattern:", "options": ["goodbye", "listen", "today", "sixteen"], "answer": "listen", "audio": None},
  {"id": "bo01-q148", "number": 148, "type": "fill_blank", "question": "_ HOLE", "answer": "W", "audio": None},
  {"id": "bo01-q149", "number": 149, "type": "image_fill", "question": "Elizabeth likes _ _ _ _ _ _ and painting in her free time.", "answer": "sewing", "audio": None},
  {"id": "bo01-q150", "number": 150, "type": "fill_blank", "question": "How _ _ _ _ _ are you? – I’m 42 kilos.", "answer": "heavy", "audio": None},
  {"id": "bo01-q151", "number": 151, "type": "word_order", "question": "Was/ farm/ last month?/ John/ on his parents’/", "answer": "Was John on his parents’ farm last month?", "audio": None},
  {"id": "bo01-q152", "number": 152, "type": "listening_multiple_choice", "question": "Where are they going?", "options": ["To the shopping centre.", "To the amusement centre.", "To the museum.", "To the stadium."], "answer": "To the amusement centre.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/1/13/636199100112342831_Audio.mp3"},
  {"id": "bo01-q153", "number": 153, "type": "listening_multiple_choice", "question": "Where does she usually work? - ....", "options": ["At the office", "At home", "At the company", "At the clinic"], "answer": "At the office", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302350774965579_Audio.mp3"},
  {"id": "bo01-q154", "number": 154, "type": "fill_blank", "question": "The stomachache prevented Mr. Thanh _ _ _ _ enjoying the meal.", "answer": "from", "audio": None},
  {"id": "bo01-q155", "number": 155, "type": "word_order", "question": "going to/ My grandparents/ are/ next Sunday./ visit us/", "answer": "My grandparents are going to visit us next Sunday.", "audio": None},
  {"id": "bo01-q156", "number": 156, "type": "word_order", "question": "a wedding/ invitation/ last week./ from my friend/ I received/", "answer": "I received a wedding invitation from my friend last week.", "audio": None},
  {"id": "bo01-q157", "number": 157, "type": "multiple_choice", "question": "Unhealthy food can ... you sick.", "options": ["do", "have", "bring", "make"], "answer": "make", "audio": None},
  {"id": "bo01-q158", "number": 158, "type": "image_fill", "question": "This is my new k_ _ _ _ _ , Dan. She is so lovely.", "answer": "itten", "audio": None},
  {"id": "bo01-q159", "number": 159, "type": "word_order", "question": "the household chores./ take me an/ hour to do/ It will/", "answer": "It will take me an hour to do the household chores.", "audio": None},
  {"id": "bo01-q160", "number": 160, "type": "fill_blank", "question": "_ _ _ _ _ is a nice souvenir shop down the street.", "answer": "There", "audio": None},
  {"id": "bo01-q161", "number": 161, "type": "multiple_choice", "question": "It rained ... last week and I couldn’t go out.", "options": ["a lot", "lots", "many", "a few"], "answer": "a lot", "audio": None},
  {"id": "bo01-q162", "number": 162, "type": "multiple_choice", "question": "My grandfather is ... man.", "options": ["old", "not young", "very young", "an old"], "answer": "an old", "audio": None},
  {"id": "bo01-q163", "number": 163, "type": "multiple_choice", "question": "Do you want some ... these cakes?", "options": ["to", "of", "with", "on"], "answer": "of", "audio": None},
  {"id": "bo01-q164", "number": 164, "type": "multiple_choice", "question": "The weather is warm enough for us ….", "options": ["to go out", "to going out", "going out", "go out"], "answer": "to go out", "audio": None},
  {"id": "bo01-q165", "number": 165, "type": "word_order", "question": "years old/ next month./ twenty-one/ will be/ He/", "answer": "He will be twenty-one years old next month.", "audio": None},
  {"id": "bo01-q166", "number": 166, "type": "word_order", "question": "eggshells./ hobby is/ Her/ carving/ mother’s/", "answer": "Her mother’s hobby is carving eggshells.", "audio": None},
  {"id": "bo01-q167", "number": 167, "type": "fill_blank", "question": "A rice paddy is also a _ _ _ _ _ field.", "answer": "paddy", "audio": None},
  {"id": "bo01-q168", "number": 168, "type": "word_order", "question": "next/ birthday./ Chi will/ be fourteen/ on her/", "answer": "Chi will be fourteen on her next birthday.", "audio": None},
  {"id": "bo01-q169", "number": 169, "type": "word_order", "question": "some money/ from/ Tom received/ his elder sister/ this morning./", "answer": "Tom received some money from his elder sister this morning.", "audio": None},
  {"id": "bo01-q170", "number": 170, "type": "fill_blank", "question": "Another word for “fall” is “au_ _ _ _ ”.", "answer": "tumn", "audio": None},
  {"id": "bo01-q171", "number": 171, "type": "fill_blank", "question": "Alexander G. Bell worked with people _ _ _ could neither speak nor hear.", "answer": "who", "audio": None},
  {"id": "bo01-q172", "number": 172, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently from the others:", "options": ["coop", "door", "food", "boot"], "answer": "door", "audio": None},
  {"id": "bo01-q173", "number": 173, "type": "multiple_choice", "question": "Thank you very much. - ….", "options": ["You welcome!", "Yours truly.", "My pleasure.", "Never mine."], "answer": "My pleasure.", "audio": None},
  {"id": "bo01-q174", "number": 174, "type": "multiple_choice", "question": "Does this drug have any unpleasant …?", "options": ["beside effects", "side effects", "beside affects", "side affects"], "answer": "side effects", "audio": None},
  {"id": "bo01-q175", "number": 175, "type": "multiple_choice", "question": "Eating fruits and vegetables are good ... our health.", "options": ["at", "with", "for", "of"], "answer": "for", "audio": None},
  {"id": "bo01-q176", "number": 176, "type": "listening_fill", "question": "I apologize if I hurt your _ _ _ _ _ _ _ _ .", "answer": "feelings", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2019-2020/Tinh_Thanhpho/L7/nghe/de1/6.mp3"},
  {"id": "bo01-q177", "number": 177, "type": "odd_one_out", "question": "Odd one out:", "options": ["Mid-Autumn", "lantern", "mooncake", "peach blossom"], "answer": "peach blossom", "audio": None},
  {"id": "bo01-q178", "number": 178, "type": "fill_blank", "question": "I have a bad cold. I keep snee_ _ _ _ .", "answer": "zing", "audio": None},
  {"id": "bo01-q179", "number": 179, "type": "fill_blank", "question": "Mrs. Lien said you could reach her _ _ 8. 545 646.", "answer": "at", "audio": None},
  {"id": "bo01-q180", "number": 180, "type": "word_order", "question": "her sister./ than/ beautiful/ Trang looks/ more/", "answer": "Trang looks more beautiful than her sister.", "audio": None},
  {"id": "bo01-q181", "number": 181, "type": "fill_blank", "question": "You have to work h_ _ _ _ _ when you grow up.", "answer": "arder", "audio": None},
  {"id": "bo01-q182", "number": 182, "type": "fill_blank", "question": "Your application must be made _ _ _ _ 3 copies for handling by our company.", "answer": "into", "audio": None},
  {"id": "bo01-q183", "number": 183, "type": "multiple_choice", "question": "We say toothache, headache and ... eyes.", "options": ["pain", "ache", "sore", "sick"], "answer": "sore", "audio": None},
  {"id": "bo01-q184", "number": 184, "type": "multiple_choice", "question": "Where is the supermarket? – It’s ... the hospital.", "options": ["right", "of the right", "the right of", "on the right of"], "answer": "on the right of", "audio": None},
  {"id": "bo01-q185", "number": 185, "type": "word_order", "question": "humid/ days in/ of Viet Nam./ February in the north/ We don’t like/", "answer": "We don’t like humid days in February in the north of Viet Nam.", "audio": None},
  {"id": "bo01-q186", "number": 186, "type": "multiple_choice", "question": "We watch movies and cartoons on ....", "options": ["radio", "black board", "TV", "the piano"], "answer": "TV", "audio": None},
  {"id": "bo01-q187", "number": 187, "type": "fill_blank", "question": "Yesterday _ _ _ Sunday and I got up very late.", "answer": "was", "audio": None},
  {"id": "bo01-q188", "number": 188, "type": "multiple_choice", "question": "Let’s go to the lunch room. I’m ….", "options": ["happy", "full", "hungry", "tired"], "answer": "hungry", "audio": None},
  {"id": "bo01-q189", "number": 189, "type": "fill_blank", "question": "Paul Anka both plays the piano _ _ _ composes music.", "answer": "and", "audio": None},
  {"id": "bo01-q190", "number": 190, "type": "multiple_choice", "question": "You have made … mistakes in your writing.", "options": ["so much", "a lot of", "little of", "much of"], "answer": "a lot of", "audio": None},
  {"id": "bo01-q191", "number": 191, "type": "word_order", "question": "and mountains/ in our country./ rivers/ a lot of/ There are/", "answer": "There are a lot of rivers and mountains in our country.", "audio": None},
  {"id": "bo01-q192", "number": 192, "type": "word_order", "question": "dreams./ you/ forget/ your/ Never should/", "answer": "Never should you forget your dreams.", "audio": None},
  {"id": "bo01-q193", "number": 193, "type": "listening_multiple_choice", "question": "What was he doing when he heard a shout? - ....", "options": ["He was teaching", "He was reading", "He was studying", "He was eating"], "answer": "He was reading", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/27/635211582703834229_Audio.mp3"},
  {"id": "bo01-q194", "number": 194, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["How is your new department different from your old one?", "How does your new flat differ from your old one?", "How does your new department different from your old one?", "How is your new flat different from your old one?"], "answer": "How is your new flat different from your old one?", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302353990287226_Audio.mp3"},
  {"id": "bo01-q195", "number": 195, "type": "listening_fill", "question": "I made a _ _ _ _ _ _ _ _ card for my dad.", "answer": "birthday", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241545041554337_Audio.mp3"},
  {"id": "bo01-q196", "number": 196, "type": "listening_fill", "question": "It is exciting to take an _ _ _ _ _ _ _ _ ride.", "answer": "airplane", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241440003685765_Audio.mp3"},
  {"id": "bo01-q197", "number": 197, "type": "multiple_choice", "question": "… lucky he is!", "options": ["What", "What a", "How", "How a"], "answer": "How", "audio": None},
  {"id": "bo01-q198", "number": 198, "type": "word_order", "question": "these pens/ Are/ and/ yours?/ rulers/", "answer": "Are these pens and rulers yours?", "audio": None},
  {"id": "bo01-q199", "number": 199, "type": "multiple_choice", "question": "I ... up late last night, so I ... up late this morning.", "options": ["stay / get", "stayed / get", "stayed / got", "stay / got"], "answer": "stayed / got", "audio": None},
  {"id": "bo01-q200", "number": 200, "type": "fill_blank", "question": "A _ _ _ _ _ bor is a person who lives near your house.", "answer": "neigh", "audio": None}
]

def get_bo01():
    questions = [normalize_question(q, 1) for q in raw_questions]
    return {
        "examId": "01",
        "setId": "bo01",
        "title": "IOE K7 2024-2025 - Đề số 01",
        "totalQuestions": len(questions),
        "questions": questions
    }
