# Raw questions for bo02
import json
from normalizer import normalize_question

raw_questions = [
  {"id": "bo02-q001", "number": 1, "type": "multiple_choice", "question": "The bus leaves at exactly 4, so ... late.", "options": ["aren’t", "won’t be", "don’t be", "didn’t"], "answer": "don’t be", "audio": None},
  {"id": "bo02-q002", "number": 2, "type": "word_order", "question": "Mr. Steve/ never/ listens/ this kind of music./ to/", "answer": "Mr. Steve never listens to this kind of music.", "audio": None},
  {"id": "bo02-q003", "number": 3, "type": "fill_blank", "question": "John is very nice. We like him a _ _ _ .", "answer": "lot", "audio": None},
  {"id": "bo02-q004", "number": 4, "type": "fill_blank", "question": "What is _ _ _ weather like in summer?", "answer": "the", "audio": None},
  {"id": "bo02-q005", "number": 5, "type": "fill_blank", "question": "I_ REGULAR", "answer": "R", "audio": None},
  {"id": "bo02-q006", "number": 6, "type": "word_order", "question": "practice/ playing/ in the afternoon?/ the piano/ Do they often/", "answer": "Do they often practice playing the piano in the afternoon?", "audio": None},
  {"id": "bo02-q007", "number": 7, "type": "fill_blank", "question": "Tom: How does Nam go to school? - Loan: He w_ _ _ _ to school every morning.", "answer": "alks", "audio": None},
  {"id": "bo02-q008", "number": 8, "type": "listening_fill", "question": "When you don’t need a light, you should _ _ _ _ _ _ it off.", "answer": "switch", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/1/8/635563324155221207_Audio.mp3"},
  {"id": "bo02-q009", "number": 9, "type": "fill_blank", "question": "Is this bed suitable _ _ _ your bedroom?", "answer": "for", "audio": None},
  {"id": "bo02-q010", "number": 10, "type": "multiple_choice", "question": "The wind blew very ….", "options": ["hard", "fast", "quickly", "soon"], "answer": "hard", "audio": None},
  {"id": "bo02-q011", "number": 11, "type": "fill_blank", "question": "Anna spend most _ _ her time studying in the library.", "answer": "of", "audio": None},
  {"id": "bo02-q012", "number": 12, "type": "fill_blank", "question": "Jim shouldn’t stay _ _ so late.", "answer": "up", "audio": None},
  {"id": "bo02-q013", "number": 13, "type": "fill_blank", "question": "Why don’t we _ _ camping this weekend?", "answer": "go", "audio": None},
  {"id": "bo02-q014", "number": 14, "type": "image_fill", "question": "He can’t _ _ _ _ because of his deafness.", "answer": "hear", "audio": None},
  {"id": "bo02-q015", "number": 15, "type": "fill_blank", "question": "IL_ NESS", "answer": "L", "audio": None},
  {"id": "bo02-q016", "number": 16, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently from the others:", "options": ["sugar", "serious", "symptom", "second"], "answer": "sugar", "audio": None},
  {"id": "bo02-q017", "number": 17, "type": "multiple_choice", "question": "In the ocean, … more salt in the deeper water.", "options": ["is there", "there is", "it may be", "it is"], "answer": "there is", "audio": None},
  {"id": "bo02-q018", "number": 18, "type": "fill_blank", "question": "He loves _ _ _ _ _ _ _ _ _ _ stamps. He has hundreds of stamps in his collection.", "answer": "collecting", "audio": None},
  {"id": "bo02-q019", "number": 19, "type": "fill_blank", "question": "Are there any lakes in the coun_ _ _ side? – A lot!", "answer": "try", "audio": None},
  {"id": "bo02-q020", "number": 20, "type": "fill_blank", "question": "I hope that he will get b_ _ _ _ _ soon.", "answer": "etter", "audio": None},
  {"id": "bo02-q021", "number": 21, "type": "multiple_choice", "question": "Farah has ... hair.", "options": ["short curly", "curly short", "short’s curly", "curl short"], "answer": "short curly", "audio": None},
  {"id": "bo02-q022", "number": 22, "type": "fill_blank", "question": "Everybody is waiting _ _ _ the president in the hall now.", "answer": "for", "audio": None},
  {"id": "bo02-q023", "number": 23, "type": "listening_multiple_choice", "question": "What can we do? - ....", "options": ["Try to stay underwater", "Try to stay away from the water", "Try to stay away from the weather", "Try to stay away from the butcher"], "answer": "Try to stay away from the water", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302348118436913_Audio.mp3"},
  {"id": "bo02-q024", "number": 24, "type": "word_order", "question": "some money/ from/ this morning./ Tom received/ his elder sister/", "answer": "Tom received some money from his elder sister this morning.", "audio": None},
  {"id": "bo02-q025", "number": 25, "type": "fill_blank", "question": "Are you taking morning ex_ _ _ _ _ _ _ often?", "answer": "ercises", "audio": None},
  {"id": "bo02-q026", "number": 26, "type": "word_order", "question": "makes/ Nam/ other people laugh/ often/ because he likes telling jokes./", "answer": "Nam often makes other people laugh because he likes telling jokes.", "audio": None},
  {"id": "bo02-q027", "number": 27, "type": "fill_blank", "question": "Excuse _ _ . Could you show me where the park is?", "answer": "me", "audio": None},
  {"id": "bo02-q028", "number": 28, "type": "word_order", "question": "is the most/ of/ interesting/ the three./ This book/", "answer": "This book is the most interesting of the three.", "audio": None},
  {"id": "bo02-q029", "number": 29, "type": "image_fill", "question": "We don’t have much time to come back home so we go to the food _ _ _ _ l for lunch.", "answer": "stal", "audio": None},
  {"id": "bo02-q030", "number": 30, "type": "word_order", "question": "lovely and/ you have!/ What a/ cozy/ house/", "answer": "What a lovely and cozy house you have!", "audio": None},
  {"id": "bo02-q031", "number": 31, "type": "multiple_choice", "question": "We are wasting too ... water.", "options": ["Ø", "many", "much", "more"], "answer": "much", "audio": None},
  {"id": "bo02-q032", "number": 32, "type": "word_order", "question": "is/ granddaughter’s/ What/ your/ age?/", "answer": "What is your granddaughter’s age?", "audio": None},
  {"id": "bo02-q033", "number": 33, "type": "multiple_choice", "question": "Be ... when you cross the road! It’s dangerous!", "options": ["quiet", "careful", "noisy", "slowly"], "answer": "careful", "audio": None},
  {"id": "bo02-q034", "number": 34, "type": "fill_blank", "question": "His brother finished high school 6 years _ _ _ .", "answer": "ago", "audio": None},
  {"id": "bo02-q035", "number": 35, "type": "word_order", "question": "realize our/ Our teachers/ try to/ full potential./ help us/", "answer": "Our teachers try to help us realize our full potential.", "audio": None},
  {"id": "bo02-q036", "number": 36, "type": "fill_blank", "question": "Does she always have lunch _ _ _ _ her friends?", "answer": "with", "audio": None},
  {"id": "bo02-q037", "number": 37, "type": "listening_multiple_choice", "question": "We listen to songs and noises with our ....", "options": ["eyes", "nose", "mouth", "ears"], "answer": "ears", "audio": None},
  {"id": "bo02-q038", "number": 38, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["drink", "favorite", "cooking", "nine"], "answer": "nine", "audio": None},
  {"id": "bo02-q039", "number": 39, "type": "multiple_choice", "question": "She is thirsty. It also means ’’She wants ....’’", "options": ["a drink", "some meat", "some potatoes", "some bread"], "answer": "a drink", "audio": None},
  {"id": "bo02-q040", "number": 40, "type": "multiple_choice", "question": "I know how to wash vegetables well! – Oh, ... me, please!", "options": ["tell", "say", "speak", "say to"], "answer": "tell", "audio": None},
  {"id": "bo02-q041", "number": 41, "type": "word_order", "question": "last Sunday./ at midnight/ ringing/ was/ The phone/", "answer": "The phone was ringing at midnight last Sunday.", "audio": None},
  {"id": "bo02-q042", "number": 42, "type": "multiple_choice", "question": "What class ... they in?", "options": ["do", "are", "is", "does"], "answer": "are", "audio": None},
  {"id": "bo02-q043", "number": 43, "type": "fill_blank", "question": "I don’t want _ _ _ much sugar in the coffee.", "answer": "too", "audio": None},
  {"id": "bo02-q044", "number": 44, "type": "multiple_choice", "question": "We … everything we can to help you!", "options": ["do", "shall do", "would do", "had done"], "answer": "shall do", "audio": None},
  {"id": "bo02-q045", "number": 45, "type": "listening_fill", "question": "I am afraid of _ _ _ _ _ .", "answer": "water", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241443922130973_Audio.mp3"},
  {"id": "bo02-q046", "number": 46, "type": "image_fill", "question": "There is a ten-_ _ _ _ _ building in front of my house.", "answer": "floor", "audio": None},
  {"id": "bo02-q047", "number": 47, "type": "word_order", "question": "all/ hard/ work/ weekdays./ Sammy and Blake/", "answer": "Sammy and Blake work hard all weekdays.", "audio": None},
  {"id": "bo02-q048", "number": 48, "type": "word_order", "question": "over/ there./ the girl/ at/ Look/", "answer": "Look at the girl over there.", "audio": None},
  {"id": "bo02-q049", "number": 49, "type": "image_fill", "question": "Don’t make a _ _ _ _ here. It’s very dangerous.", "answer": "fire", "audio": None},
  {"id": "bo02-q050", "number": 50, "type": "fill_blank", "question": "I am trying to solve this math problem but I know my answer isn’t _ _ _ ht.", "answer": "rig", "audio": None},
  {"id": "bo02-q051", "number": 51, "type": "word_order", "question": "Uyen/ everyday./ a bus/ takes/ to school/", "answer": "Uyen takes a bus to school everyday.", "audio": None},
  {"id": "bo02-q052", "number": 52, "type": "word_order", "question": "you pass/ the post office./ me an envelope and/ Please buy/ some stamps when/", "answer": "Please buy me an envelope and some stamps when you pass the post office.", "audio": None},
  {"id": "bo02-q053", "number": 53, "type": "word_order", "question": "one of/ think of/ you as/ I always/ the family./", "answer": "I always think of you as one of the family.", "audio": None},
  {"id": "bo02-q054", "number": 54, "type": "fill_blank", "question": "I’m going to learn to drive. I never had time to learn _ _ _ _ I was younger.", "answer": "when", "audio": None},
  {"id": "bo02-q055", "number": 55, "type": "multiple_choice", "question": "Hung and Hieu are ….", "options": ["a student", "an student", "student", "students"], "answer": "students", "audio": None},
  {"id": "bo02-q056", "number": 56, "type": "odd_one_out", "question": "Odd one out:", "options": ["gift", "present", "store", "souvenir"], "answer": "store", "audio": None},
  {"id": "bo02-q057", "number": 57, "type": "multiple_choice", "question": "Wake up” has similar meaning to “...”.", "options": ["stay up", "get up", "pick up", "keep up"], "answer": "get up", "audio": None},
  {"id": "bo02-q058", "number": 58, "type": "multiple_choice", "question": "’’What do you intend to do this weekend?’’ also means ’’...’’.", "options": ["What do you do this weekend?", "What are you going to do this weekend?", "What has you do this weekend?", "What are you doing this weekend?"], "answer": "What are you going to do this weekend?", "audio": None},
  {"id": "bo02-q059", "number": 59, "type": "fill_blank", "question": "Your Dad and I hope you _ _ _ well.", "answer": "are", "audio": None},
  {"id": "bo02-q060", "number": 60, "type": "stress", "question": "Choose the word which has different stress pattern:", "options": ["example", "discovery", "performance", "magazine"], "answer": "magazine", "audio": None},
  {"id": "bo02-q061", "number": 61, "type": "multiple_choice", "question": "We have lots of ... in summer.", "options": ["the rain", "raining", "rainy", "rain"], "answer": "rain", "audio": None},
  {"id": "bo02-q062", "number": 62, "type": "word_order", "question": "to come/ house for/ Would you like/ dinner?/ over my/", "answer": "Would you like to come over my house for dinner?", "audio": None},
  {"id": "bo02-q063", "number": 63, "type": "word_order", "question": "at birth?/ How much/ baby elephant/ weigh/ does a/", "answer": "How much does a baby elephant weigh at birth?", "audio": None},
  {"id": "bo02-q064", "number": 64, "type": "fill_blank", "question": "I don’t know what _ _ _ _ _ to buy for her birthday.", "answer": "skirt", "audio": None},
  {"id": "bo02-q065", "number": 65, "type": "fill_blank", "question": "The secretary took a message _ _ her boss.", "answer": "to", "audio": None},
  {"id": "bo02-q066", "number": 66, "type": "multiple_choice", "question": "Dogs are ... pets.", "options": ["friendly", "friend", "friend’", "friends"], "answer": "friendly", "audio": None},
  {"id": "bo02-q067", "number": 67, "type": "listening_multiple_choice", "question": "What did people do before the TV programs finished? - ....", "options": ["Someone went home", "No one went home", "Everyone went home", "Only one person went home"], "answer": "No one went home", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302336491736492_Audio.mp3"},
  {"id": "bo02-q068", "number": 68, "type": "fill_blank", "question": "What are you looking _ _ _ ? – I’ve lost my pencil.", "answer": "for", "audio": None},
  {"id": "bo02-q069", "number": 69, "type": "word_order", "question": "cost/ six/ Six bananas/ dollars./ me/", "answer": "Six bananas cost me six dollars.", "audio": None},
  {"id": "bo02-q070", "number": 70, "type": "image_fill", "question": "How much is it to make this _ _ _ _ et skirt?", "answer": "viol", "audio": None},
  {"id": "bo02-q071", "number": 71, "type": "word_order", "question": "There are/ for young/ people./ many kinds/ of entertainment/", "answer": "There are many kinds of entertainment for young people.", "audio": None},
  {"id": "bo02-q072", "number": 72, "type": "fill_blank", "question": "Zidane is _ _ _ _ _ the greatest football players in the world.", "answer": "among", "audio": None},
  {"id": "bo02-q073", "number": 73, "type": "fill_blank", "question": "Many women in Vietnam often stay at home to take care of the house and look _ _ _ _ _ their children.", "answer": "after", "audio": None},
  {"id": "bo02-q074", "number": 74, "type": "fill_blank", "question": "Whose book is this, yours or m_ _ _ ?", "answer": "ine", "audio": None},
  {"id": "bo02-q075", "number": 75, "type": "fill_blank", "question": "I don’t know _ _ _ to use this machine. It’s too complex!", "answer": "how", "audio": None},
  {"id": "bo02-q076", "number": 76, "type": "multiple_choice", "question": "Such a hard working day. I … to go straight to bed right now.", "options": ["am wanting", "wants", "wanted", "want"], "answer": "want", "audio": None},
  {"id": "bo02-q077", "number": 77, "type": "listening_fill", "question": "Do people have the right to smoke in _ _ _ _ _ _ ?", "answer": "public", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241442157911298_Audio.mp3"},
  {"id": "bo02-q078", "number": 78, "type": "word_order", "question": "me./ helping/ I want/ you for/ to thank/", "answer": "I want to thank you for helping me.", "audio": None},
  {"id": "bo02-q079", "number": 79, "type": "fill_blank", "question": "They have fish _ _ _ crab for lunch.", "answer": "and", "audio": None},
  {"id": "bo02-q080", "number": 80, "type": "listening_fill", "question": "I have a sore throat and _ _ _ _ _ nose.", "answer": "runny", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2019-2020/Tinh_Thanhpho/L7/nghe/de1/9.mp3"},
  {"id": "bo02-q081", "number": 81, "type": "fill_blank", "question": "We say k_ _ _ fit and stay healthy.", "answer": "eep", "audio": None},
  {"id": "bo02-q082", "number": 82, "type": "fill_blank", "question": "It’s raining. You must wear a ra_ _ _ _ _ _ .", "answer": "incoat", "audio": None},
  {"id": "bo02-q083", "number": 83, "type": "fill_blank", "question": "My aunt has two children, one boy and one _ _ _ _ .", "answer": "girl", "audio": None},
  {"id": "bo02-q084", "number": 84, "type": "word_order", "question": "taste fresh/ These/ to us./ don’t/ vegetables/", "answer": "These vegetables don’t taste fresh to us.", "audio": None},
  {"id": "bo02-q085", "number": 85, "type": "fill_blank", "question": "’’How are you?’’ – ’’Very well, _ _ _ _ _ you. And you?’’", "answer": "thank", "audio": None},
  {"id": "bo02-q086", "number": 86, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["Their children usually play at home in the evening.", "Their children may be at home in the evening.", "Their children usually stay at home in the evening.", "Their children only stay at home in the evening."], "answer": "Their children usually stay at home in the evening.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302358979643990_Audio.mp3"},
  {"id": "bo02-q087", "number": 87, "type": "listening_fill", "question": "I _ _ _ _ out the clothes on the clothesline.", "answer": "hung", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241436203990911_Audio.mp3"},
  {"id": "bo02-q088", "number": 88, "type": "word_order", "question": "than four books/ with just one/ You can’t/ library card./ borrow more/", "answer": "You can’t borrow more than four books with just one library card.", "audio": None},
  {"id": "bo02-q089", "number": 89, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["pear", "hear", "early", "clear"], "answer": "early", "audio": None},
  {"id": "bo02-q090", "number": 90, "type": "word_order", "question": "can speak both/ English and/ Chinese./ people in Singapore/ A lot of/", "answer": "A lot of people in Singapore can speak both English and Chinese.", "audio": None},
  {"id": "bo02-q091", "number": 91, "type": "multiple_choice", "question": "This semester will last ... 6 months.", "options": ["in", "on", "at", "for"], "answer": "for", "audio": None},
  {"id": "bo02-q092", "number": 92, "type": "multiple_choice", "question": "What’s spring like in Hanoi? - ….", "options": ["I like travelling in spring.", "It’s warm.", "Spring likes flowers.", "It’s from January to March."], "answer": "It’s warm.", "audio": None},
  {"id": "bo02-q093", "number": 93, "type": "fill_blank", "question": "She has to use a ca_ _ _ _ _ _ _ _ to do Math exercises.", "answer": "lculator", "audio": None},
  {"id": "bo02-q094", "number": 94, "type": "multiple_choice", "question": "He sat there and watched the artist … the whole picture.", "options": ["drawed", "to draw", "draws", "drawing"], "answer": "drawing", "audio": None},
  {"id": "bo02-q095", "number": 95, "type": "image_fill", "question": "My cat Molly is drinking _ _ _ _ from its bowl.", "answer": "milk", "audio": None},
  {"id": "bo02-q096", "number": 96, "type": "word_order", "question": "at night./ go/ alone/ Janet doesn’t/ want me to/", "answer": "Janet doesn’t want me to go alone at night.", "audio": None},
  {"id": "bo02-q097", "number": 97, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["buffalo", "pull", "struture", "uncle"], "answer": "pull", "audio": None},
  {"id": "bo02-q098", "number": 98, "type": "multiple_choice", "question": "I am ... of hearing ghost stories.", "options": ["boring", "interested", "scared", "careful"], "answer": "scared", "audio": None},
  {"id": "bo02-q099", "number": 99, "type": "fill_blank", "question": "Minh was _ _ _ _ nt from school for two days due to his illness.", "answer": "abse", "audio": None},
  {"id": "bo02-q100", "number": 100, "type": "multiple_choice", "question": "Baseball is different … soccer.", "options": ["from", "of", "for", "with"], "answer": "from", "audio": None},
  {"id": "bo02-q101", "number": 101, "type": "listening_multiple_choice", "question": "What does his brother study hard for? - ....", "options": ["Getting good marks", "Passing the final exam at university", "Passing the entrance exam to the university", "Studying abroad"], "answer": "Passing the entrance exam to the university", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/27/635211653295362217_Audio.mp3"},
  {"id": "bo02-q102", "number": 102, "type": "multiple_choice", "question": "My mother doesn’t like coffee and ….", "options": ["neither do I", "neither I do", "either do I", "I don’t too"], "answer": "neither do I", "audio": None},
  {"id": "bo02-q103", "number": 103, "type": "fill_blank", "question": "What _ _ _ _ _ going by bus? – Nice idea!", "answer": "about", "audio": None},
  {"id": "bo02-q104", "number": 104, "type": "listening_multiple_choice", "question": "The boy will be allowed to plays sports after ….", "options": ["he has helped his mother with the housework", "he has finished all his work", "he has finished his classes", "he has tidied his bedroom"], "answer": "he has finished all his work", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/12/8/636168092334981203_Audio.mp3"},
  {"id": "bo02-q105", "number": 105, "type": "word_order", "question": "couple is/ the street./ slowly walking/ A young/ along/", "answer": "A young couple is slowly walking along the street.", "audio": None},
  {"id": "bo02-q106", "number": 106, "type": "multiple_choice", "question": "Some students say they are …. They have no time for relaxation.", "options": ["hurry", "busy", "full", "hard"], "answer": "busy", "audio": None},
  {"id": "bo02-q107", "number": 107, "type": "image_fill", "question": "John: What music instrument can you play? - Linh: I can play the o_ _ _ _ .", "answer": "rgan", "audio": None},
  {"id": "bo02-q108", "number": 108, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["wear", "clear", "dear", "appear"], "answer": "wear", "audio": None},
  {"id": "bo02-q109", "number": 109, "type": "word_order", "question": "and sugar./ vegetables and/ eat more/ less meat/ We should/", "answer": "We should eat more vegetables and less meat and sugar.", "audio": None},
  {"id": "bo02-q110", "number": 110, "type": "multiple_choice", "question": "Don’t ... water.", "options": ["throw", "drip", "leave", "waste"], "answer": "waste", "audio": None},
  {"id": "bo02-q111", "number": 111, "type": "word_order", "question": "are going to/ stay in a/ seafood there./ My family/ hotel and have/", "answer": "My family are going to stay in a hotel and have seafood there.", "audio": None},
  {"id": "bo02-q112", "number": 112, "type": "multiple_choice", "question": "The principal should … the speech of welcome first.", "options": ["do", "make", "have", "speak"], "answer": "make", "audio": None},
  {"id": "bo02-q113", "number": 113, "type": "multiple_choice", "question": "… our house for us is the most suitable thing.", "options": ["Build", "Built", "To build", "You build"], "answer": "To build", "audio": None},
  {"id": "bo02-q114", "number": 114, "type": "listening_multiple_choice", "question": "What is the time? - ....", "options": ["It’s a quarter to seven now.", "It’s a quarter to eleven now.", "It’s a quarter past seven now.", "It’s a quarter past eleven now."], "answer": "It’s a quarter to seven now.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/3/6/635612600623459566_Audio.mp3"},
  {"id": "bo02-q115", "number": 115, "type": "fill_blank", "question": "Playing with one match can start _ fire.", "answer": "a", "audio": None},
  {"id": "bo02-q116", "number": 116, "type": "fill_blank", "question": "Long _ _ _ _ down the stairs this morning and broke his leg.", "answer": "fell", "audio": None},
  {"id": "bo02-q117", "number": 117, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["happy", "baby", "ready", "cry"], "answer": "cry", "audio": None},
  {"id": "bo02-q118", "number": 118, "type": "fill_blank", "question": "BLI_ D", "answer": "N", "audio": None},
  {"id": "bo02-q119", "number": 119, "type": "fill_blank", "question": "Will you pick me _ _ after the party?", "answer": "up", "audio": None},
  {"id": "bo02-q120", "number": 120, "type": "word_order", "question": "It’s important/ a book./ for every/ student/ to have/", "answer": "It’s important for every student to have a book.", "audio": None},
  {"id": "bo02-q121", "number": 121, "type": "multiple_choice", "question": "Yesterday they had a ... check-up at school.", "options": ["medicine", "medicines", "medical", "medically"], "answer": "medical", "audio": None},
  {"id": "bo02-q122", "number": 122, "type": "fill_blank", "question": "I _ _ _ _ off my shoes because they were dirty.", "answer": "took", "audio": None},
  {"id": "bo02-q123", "number": 123, "type": "listening_fill", "question": "Some people decide to give up _ _ _ _ _ _ _ .", "answer": "smoking", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241439723997849_Audio.mp3"},
  {"id": "bo02-q124", "number": 124, "type": "fill_blank", "question": "M_ NUTE", "answer": "I", "audio": None},
  {"id": "bo02-q125", "number": 125, "type": "fill_blank", "question": "There is too much _ _ _ _ _ in my coffee. It is too sweet.", "answer": "sugar", "audio": None},
  {"id": "bo02-q126", "number": 126, "type": "fill_blank", "question": "Because Jim is _ _ _ _ _ - sighted, he can’t read what is on the boars.", "answer": "short", "audio": None},
  {"id": "bo02-q127", "number": 127, "type": "word_order", "question": "to do/ two hours/ It takes her/ each day/ her homework./", "answer": "It takes her two hours each day to do her homework.", "audio": None},
  {"id": "bo02-q128", "number": 128, "type": "fill_blank", "question": "He wrote his most famous plays between 1999 _ _ _ 2005.", "answer": "and", "audio": None},
  {"id": "bo02-q129", "number": 129, "type": "listening_fill", "question": "She would like me not to make _ _ _ _ _ _ _ _ .", "answer": "mistakes", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241440966346584_Audio.mp3"},
  {"id": "bo02-q130", "number": 130, "type": "fill_blank", "question": "My sister is one meter 45 _ _ _ _ _ meters tall.", "answer": "centi", "audio": None},
  {"id": "bo02-q131", "number": 131, "type": "word_order", "question": "day because/ They walk to/ school every/ their houses aren’t/ far from school./", "answer": "They walk to school every day because their houses aren’t far from school.", "audio": None},
  {"id": "bo02-q132", "number": 132, "type": "word_order", "question": "to the museum,/ Can/ you tell/ me the way/ Michael?/", "answer": "Can you tell me the way to the museum, Michael?", "audio": None},
  {"id": "bo02-q133", "number": 133, "type": "odd_one_out", "question": "Odd one out:", "options": ["classroom", "teacher", "doctor", "farmer"], "answer": "classroom", "audio": None},
  {"id": "bo02-q134", "number": 134, "type": "fill_blank", "question": "When it becomes hot, people often feel th_ _ _ _ _ .", "answer": "irsty", "audio": None},
  {"id": "bo02-q135", "number": 135, "type": "word_order", "question": "the morning./ regularly at/ eight in/ The post/ arrives/", "answer": "The post arrives regularly at eight in the morning.", "audio": None},
  {"id": "bo02-q136", "number": 136, "type": "fill_blank", "question": "I often have a runny _ _ _ _ when I catch the flu.", "answer": "nose", "audio": None},
  {"id": "bo02-q137", "number": 137, "type": "word_order", "question": "outside/ in the garden./ weather is good,/ When the/ we eat/", "answer": "When the weather is good, we eat outside in the garden.", "audio": None},
  {"id": "bo02-q138", "number": 138, "type": "word_order", "question": "He should stop/ a headache./ playing/ video games./ Phong has/", "answer": "Phong has a headache. He should stop playing video games.", "audio": None},
  {"id": "bo02-q139", "number": 139, "type": "fill_blank", "question": "What’s this? - _ _ ’s a desk.", "answer": "it", "audio": None},
  {"id": "bo02-q140", "number": 140, "type": "multiple_choice", "question": "The old woman explained to us ... to the police station.", "options": ["how can get", "how we can", "how can we", "how to get"], "answer": "how to get", "audio": None},
  {"id": "bo02-q141", "number": 141, "type": "listening_multiple_choice", "question": "What does she sometimes do? - ....", "options": ["She sometimes plays chess with me", "She sometimes stresses with me", "She sometimes has a rest with me", "She sometimes plays mind test with me"], "answer": "She sometimes plays chess with me", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302349432739221_Audio.mp3"},
  {"id": "bo02-q142", "number": 142, "type": "multiple_choice", "question": "She … here next year.", "options": ["will be", "was", "is", "were"], "answer": "will be", "audio": None},
  {"id": "bo02-q143", "number": 143, "type": "multiple_choice", "question": "It’s a good movie” has similar meaning to “...”.", "options": ["It’s a boring film", "It’s an interesting film", "It’s a long film", "It’s an awful film"], "answer": "It’s an interesting film", "audio": None},
  {"id": "bo02-q144", "number": 144, "type": "multiple_choice", "question": "We can see planes parking in the ....", "options": ["airport", "railway station", "bus stop", "stadium"], "answer": "airport", "audio": None},
  {"id": "bo02-q145", "number": 145, "type": "listening_multiple_choice", "question": "When does International Friendship Day take place?", "options": ["The first Saturday in August.", "The third Sunday in July.", "The third Saturday in July.", "The first Sunday in August."], "answer": "The first Sunday in August.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/12/8/636168091292480828_Audio.mp3"},
  {"id": "bo02-q146", "number": 146, "type": "multiple_choice", "question": "What happened to you yesterday? – Oh, I had a ... cold.", "options": ["ill", "sick", "bad", "awful"], "answer": "bad", "audio": None},
  {"id": "bo02-q147", "number": 147, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently from the others:", "options": ["naked", "sacred", "wanted", "walked"], "answer": "walked", "audio": None},
  {"id": "bo02-q148", "number": 148, "type": "fill_blank", "question": "She _ _ _ _ _ _ _ many of her old friends to her birthday party on Saturday.", "answer": "invited", "audio": None},
  {"id": "bo02-q149", "number": 149, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["A man is buying some stamps.", "A woman is buying a stamp.", "A woman is buying some hens.", "A woman is buying some stamps."], "answer": "A woman is buying some stamps.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/29/635213176094220871_Audio.mp3"},
  {"id": "bo02-q150", "number": 150, "type": "word_order", "question": "in his/ week’s plan./ Adam is/ room making/ his next/", "answer": "Adam is in his room making his next week’s plan.", "audio": None},
  {"id": "bo02-q151", "number": 151, "type": "word_order", "question": "days off/ My father/ has fewer/ father./ than Tim’s/", "answer": "My father has fewer days off than Tim’s father.", "audio": None},
  {"id": "bo02-q152", "number": 152, "type": "multiple_choice", "question": "What time does his class end? – At ....", "options": ["afternoon", "evening", "night", "11 AM"], "answer": "11 AM", "audio": None},
  {"id": "bo02-q153", "number": 153, "type": "image_fill", "question": "My father always has a lot of _ _ _ _ _ _ _ _ _ to do.", "answer": "housework", "audio": None},
  {"id": "bo02-q154", "number": 154, "type": "multiple_choice", "question": "What’s your new teacher ...? – She’s very pretty.", "options": ["like", "likes", "liking", "would like"], "answer": "like", "audio": None},
  {"id": "bo02-q155", "number": 155, "type": "multiple_choice", "question": "It’s difficult to cross this street because there is too much … .", "options": ["crowd", "traffic", "people", "transport"], "answer": "traffic", "audio": None},
  {"id": "bo02-q156", "number": 156, "type": "multiple_choice", "question": "How … is it from Hanoi to Hue City?", "options": ["many", "long", "far", "much"], "answer": "far", "audio": None},
  {"id": "bo02-q157", "number": 157, "type": "listening_multiple_choice", "question": "Where does Jane usually work? - ....", "options": ["in England", "in Holland", "in Poland", "in Ireland"], "answer": "in England", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302350408676935_Audio.mp3"},
  {"id": "bo02-q158", "number": 158, "type": "multiple_choice", "question": "How long did he stay in his uncle’s farm? – He stayed for ....", "options": ["yesterday", "last week", "last year", "a week"], "answer": "a week", "audio": None},
  {"id": "bo02-q159", "number": 159, "type": "multiple_choice", "question": "She has a shower and gets ....", "options": ["dressed", "dresses", "dress", "dressing"], "answer": "dressed", "audio": None},
  {"id": "bo02-q160", "number": 160, "type": "fill_blank", "question": "These medicines can help re_ _ _ ve the symptoms of the flu.", "answer": "lie", "audio": None},
  {"id": "bo02-q161", "number": 161, "type": "fill_blank", "question": "Please read the dialo_ _ _ and answer the questions below.", "answer": "gue", "audio": None},
  {"id": "bo02-q162", "number": 162, "type": "multiple_choice", "question": "How much pork does she need? – ....", "options": ["A tube", "A kilo", "A packet", "A dozen"], "answer": "A kilo", "audio": None},
  {"id": "bo02-q163", "number": 163, "type": "word_order", "question": "April/ Today/ is/ 11th of/ 2015./", "answer": "Today is 11th of April 2015.", "audio": None},
  {"id": "bo02-q164", "number": 164, "type": "word_order", "question": "and watch/ My sisters/ TV/ just sit/ all evening./", "answer": "My sisters just sit and watch TV all evening.", "audio": None},
  {"id": "bo02-q165", "number": 165, "type": "multiple_choice", "question": "Can you give me …?", "options": ["a ride", "a drive", "riding", "driving"], "answer": "a ride", "audio": None},
  {"id": "bo02-q166", "number": 166, "type": "word_order", "question": "important/ the most/ What is/ festival in/ your country?/", "answer": "What is the most important festival in your country?", "audio": None},
  {"id": "bo02-q167", "number": 167, "type": "listening_multiple_choice", "question": "What are there on the farm? - ....", "options": ["Corns and beans", "Corns and sugar canes", "Rice and beans", "Rice and corns"], "answer": "Corns and sugar canes", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/27/635211657063080834_Audio.mp3"},
  {"id": "bo02-q168", "number": 168, "type": "word_order", "question": "small package/ does a/ How much/ cost?/ to London/", "answer": "How much does a small package to London cost?", "audio": None},
  {"id": "bo02-q169", "number": 169, "type": "fill_blank", "question": "Please fill in your medical _ _ _ _ _ ds for having a medical check-up.", "answer": "recor", "audio": None},
  {"id": "bo02-q170", "number": 170, "type": "fill_blank", "question": "Jim shouldn’t stay _ _ so late.", "answer": "up", "audio": None},
  {"id": "bo02-q171", "number": 171, "type": "multiple_choice", "question": "… his friends are over 50 years old.", "options": ["Little", "A lot", "Most", "Most of"], "answer": "Most of", "audio": None},
  {"id": "bo02-q172", "number": 172, "type": "word_order", "question": "out of/ slipped/ The dish/ my hand/ onto the floor./", "answer": "The dish slipped out of my hand onto the floor.", "audio": None},
  {"id": "bo02-q173", "number": 173, "type": "multiple_choice", "question": "The … student will spend long hours in library and seldom accept invitations to go out.", "options": ["careless", "thoughtful", "dedicated", "guilty"], "answer": "dedicated", "audio": None},
  {"id": "bo02-q174", "number": 174, "type": "multiple_choice", "question": "Children … good food to be healthy.", "options": ["have", "receive", "eat", "need"], "answer": "need", "audio": None},
  {"id": "bo02-q175", "number": 175, "type": "fill_blank", "question": "I’d like a sandw_ _ _ and a glass of lemonade.", "answer": "ich", "audio": None},
  {"id": "bo02-q176", "number": 176, "type": "word_order", "question": "success./ find your/ I hope/ you will/ way to/", "answer": "I hope you will find your way to success.", "audio": None},
  {"id": "bo02-q177", "number": 177, "type": "fill_blank", "question": "He’s a worker. She’s a worker, _ _ _ .", "answer": "too", "audio": None},
  {"id": "bo02-q178", "number": 178, "type": "multiple_choice", "question": "… did it take you to finish the project? – Just one day.", "options": ["How many", "How much", "How long", "How often"], "answer": "How long", "audio": None},
  {"id": "bo02-q179", "number": 179, "type": "fill_blank", "question": "W_ _ _ _ park will you take him to?", "answer": "hich", "audio": None},
  {"id": "bo02-q180", "number": 180, "type": "word_order", "question": "difficult,/ problem looks/ but let's/ give it a try./ That math/", "answer": "That math problem looks difficult, but let's give it a try.", "audio": None},
  {"id": "bo02-q181", "number": 181, "type": "fill_blank", "question": "I can’t use the washing machine. Can you _ _ _ it?", "answer": "fix", "audio": None},
  {"id": "bo02-q182", "number": 182, "type": "word_order", "question": "team?/ school/ Does he/ for our/ play football/", "answer": "Does he play football for our school team?", "audio": None},
  {"id": "bo02-q183", "number": 183, "type": "multiple_choice", "question": "Our teacher ... us to read this passage and do exercises.", "options": ["spoke", "talked", "said", "told"], "answer": "told", "audio": None},
  {"id": "bo02-q184", "number": 184, "type": "multiple_choice", "question": "The synonym of ’’fix’’ is:", "options": ["mend", "solve", "damage", "make"], "answer": "mend", "audio": None},
  {"id": "bo02-q185", "number": 185, "type": "word_order", "question": "years/ the Earth thousands/ Dinosaurs/ lived on/ ago./", "answer": "Dinosaurs lived on the Earth thousands years ago.", "audio": None},
  {"id": "bo02-q186", "number": 186, "type": "word_order", "question": "a week/ for business./ travels to/ This man/ Hanoi twice/", "answer": "This man travels to Hanoi twice a week for business.", "audio": None},
  {"id": "bo02-q187", "number": 187, "type": "multiple_choice", "question": "It’s late. I want to go ... now.", "options": ["for", "to", "Ø", "at"], "answer": "Ø", "audio": None},
  {"id": "bo02-q188", "number": 188, "type": "multiple_choice", "question": "In the future, machines … all the work for us.", "options": ["are doing", "will do", "were doing", "do"], "answer": "will do", "audio": None},
  {"id": "bo02-q189", "number": 189, "type": "word_order", "question": "take me an/ the household chores./ It will/ hour to do/", "answer": "It will take me an hour to do the household chores.", "audio": None},
  {"id": "bo02-q190", "number": 190, "type": "fill_blank", "question": "How can I _ _ _ to the bus station? – Go straight ahead.", "answer": "get", "audio": None},
  {"id": "bo02-q191", "number": 191, "type": "listening_fill", "question": "He said that I looked very _ _ _ _ _ with the brown paper bag stuck to my face.", "answer": "funny", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/2/23/636865178138291740_Audio.mp3"},
  {"id": "bo02-q192", "number": 192, "type": "word_order", "question": "him/ smiled/ at/ The dentist/ kindly./", "answer": "The dentist smiled at him kindly.", "audio": None},
  {"id": "bo02-q193", "number": 193, "type": "fill_blank", "question": "This book is different _ _ _ _ the one I had.", "answer": "from", "audio": None},
  {"id": "bo02-q194", "number": 194, "type": "word_order", "question": "This is/ one of/ many/ nice lakes/ in Hanoi./", "answer": "This is one of many nice lakes in Hanoi.", "audio": None},
  {"id": "bo02-q195", "number": 195, "type": "fill_blank", "question": "_ ORRIBLE", "answer": "H", "audio": None},
  {"id": "bo02-q196", "number": 196, "type": "word_order", "question": "to go to/ 30 minutes/ It often/ school by bike./ takes him/", "answer": "It often takes him 30 minutes to go to school by bike.", "audio": None},
  {"id": "bo02-q197", "number": 197, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["We usually go out for dinner at the weekends.", "We usually have dinner together at the weekends.", "We usually have hamburger for dinner at the weekends.", "We usually have dinner at home at the weekends."], "answer": "We usually go out for dinner at the weekends.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302358398230968_Audio.mp3"},
  {"id": "bo02-q198", "number": 198, "type": "word_order", "question": "at night./ very/ late/ closes/ This shop/", "answer": "This shop closes very late at night.", "audio": None},
  {"id": "bo02-q199", "number": 199, "type": "multiple_choice", "question": "Nick was very ill so the doctor ... his temperature.", "options": ["had", "took", "hold", "pulled"], "answer": "took", "audio": None},
  {"id": "bo02-q200", "number": 200, "type": "fill_blank", "question": "I have fewer stamps _ _ _ _ he does.", "answer": "than", "audio": None}
]

def get_bo02():
    questions = [normalize_question(q, 2) for q in raw_questions]
    return {
        "examId": "02",
        "setId": "bo02",
        "title": "IOE K7 2024-2025 - Đề số 02",
        "totalQuestions": len(questions),
        "questions": questions
    }
