# Raw questions for bo03
import json
from normalizer import normalize_question

raw_questions = [
  {"id": "bo03-q001", "number": 1, "type": "fill_blank", "question": "We usually _ _ _ _ a picnic when we have free time.", "answer": "have", "audio": None},
  {"id": "bo03-q002", "number": 2, "type": "word_order", "question": "for/ you/ I’ll wait/ the stadium./ outside/", "answer": "I’ll wait for you outside the stadium.", "audio": None},
  {"id": "bo03-q003", "number": 3, "type": "fill_blank", "question": "It takes _ _ 10 minutes to walk to school.", "answer": "me", "audio": None},
  {"id": "bo03-q004", "number": 4, "type": "fill_blank", "question": "She bought some souvenirs _ _ _ _ the shop and so did I.", "answer": "from", "audio": None},
  {"id": "bo03-q005", "number": 5, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["youth", "thank", "there", "thirsty"], "answer": "there", "audio": None},
  {"id": "bo03-q006", "number": 6, "type": "word_order", "question": "year?/ How many/ days holiday/ got this/ have you/", "answer": "How many days holiday have you got this year?", "audio": None},
  {"id": "bo03-q007", "number": 7, "type": "fill_blank", "question": "Whose book is this, yours or m_ _ _ ?", "answer": "ine", "audio": None},
  {"id": "bo03-q008", "number": 8, "type": "word_order", "question": "How many trees/ plant/ did/ your uncle/ in his garden?/", "answer": "How many trees did your uncle plant in his garden?", "audio": None},
  {"id": "bo03-q009", "number": 9, "type": "image_fill", "question": "Tom: I’ve got an animal. It is black and white and it lives in Africa. What animal is it? - Loan: I guess it is a _ _ _ _ _ .", "answer": "zebra", "audio": None},
  {"id": "bo03-q010", "number": 10, "type": "multiple_choice", "question": "How much pork does she need? – ....", "options": ["A tube", "A kilo", "A packet", "A dozen"], "answer": "A kilo", "audio": None},
  {"id": "bo03-q011", "number": 11, "type": "fill_blank", "question": "_ _ _ often do you go to the movies? – Once a week.", "answer": "how", "audio": None},
  {"id": "bo03-q012", "number": 12, "type": "multiple_choice", "question": "You don’t need to buy anything for your room. It is ….", "options": ["boring", "delicious", "awfu", "furnished"], "answer": "furnished", "audio": None},
  {"id": "bo03-q013", "number": 13, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["Today I go to the library and borrow some story books.", "Today I go to the library and chose some scary books.", "Today I go to the library and choose some story books.", "Today I goes to the library and chooses some story books."], "answer": "Today I go to the library and choose some story books.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/29/635213183821850444_Audio.mp3"},
  {"id": "bo03-q014", "number": 14, "type": "fill_blank", "question": "I’m back _ _ _ _ school and I’m hungry.", "answer": "from", "audio": None},
  {"id": "bo03-q015", "number": 15, "type": "fill_blank", "question": "John is very nice. We like him a _ _ _ .", "answer": "lot", "audio": None},
  {"id": "bo03-q016", "number": 16, "type": "fill_blank", "question": "VIRU_", "answer": "S", "audio": None},
  {"id": "bo03-q017", "number": 17, "type": "listening_multiple_choice", "question": "What does he like doing? - ....", "options": ["Telling lies", "Telling jokes", "Making jokes", "Telling truth"], "answer": "Telling jokes", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/1/9/635563971462394238_Audio.mp3"},
  {"id": "bo03-q018", "number": 18, "type": "word_order", "question": "city has/ The public/ thousands of/ library in the/ good books./", "answer": "The public library in the city has thousands of good books.", "audio": None},
  {"id": "bo03-q019", "number": 19, "type": "fill_blank", "question": "HARV_ ST", "answer": "E", "audio": None},
  {"id": "bo03-q020", "number": 20, "type": "multiple_choice", "question": "We don’t have English ... Tuesday.", "options": ["at", "in", "on", "under"], "answer": "on", "audio": None},
  {"id": "bo03-q021", "number": 21, "type": "fill_blank", "question": "I’d rather stay at home _ _ _ _ work for him.", "answer": "than", "audio": None},
  {"id": "bo03-q022", "number": 22, "type": "word_order", "question": "going to/ next Sunday./ My grandparents/ are/ visit us/", "answer": "My grandparents are going to visit us next Sunday.", "audio": None},
  {"id": "bo03-q023", "number": 23, "type": "word_order", "question": "interesting books/ They/ have read/ several times./ those/", "answer": "They have read those interesting books several times.", "audio": None},
  {"id": "bo03-q024", "number": 24, "type": "multiple_choice", "question": "My school is at ….", "options": ["30 Hoang Hoa Tham Road", "Hoan Kiem District", "a village far from here", "Nam Dinh Province"], "answer": "30 Hoang Hoa Tham Road", "audio": None},
  {"id": "bo03-q025", "number": 25, "type": "word_order", "question": "to the nearest/ tell me/ post office?/ how to get/ Could you/", "answer": "Could you tell me how to get to the nearest post office?", "audio": None},
  {"id": "bo03-q026", "number": 26, "type": "fill_blank", "question": "Mr. Pike often takes his sons to the _ _ _ to see wild animals.", "answer": "zoo", "audio": None},
  {"id": "bo03-q027", "number": 27, "type": "multiple_choice", "question": "Will you help me … the floor?", "options": ["clean", "not clean", "cleaning", "cleaned"], "answer": "clean", "audio": None},
  {"id": "bo03-q028", "number": 28, "type": "word_order", "question": "There are/ seven of/ us altogether/ in the/ family./", "answer": "There are seven of us altogether in the family.", "audio": None},
  {"id": "bo03-q029", "number": 29, "type": "multiple_choice", "question": "John enjoys … tennis.", "options": ["playing", "play", "played", "to play"], "answer": "playing", "audio": None},
  {"id": "bo03-q030", "number": 30, "type": "fill_blank", "question": "My father is a mechanic. He _ _ _ _ _ for a factory in the suburb.", "answer": "works", "audio": None},
  {"id": "bo03-q031", "number": 31, "type": "word_order", "question": "ask him/ call/ Could you/ to/ me back?/", "answer": "Could you ask him to call me back?", "audio": None},
  {"id": "bo03-q032", "number": 32, "type": "fill_blank", "question": "Would you show me aro_ _ _ the city when I visit you? – Sure!", "answer": "und", "audio": None},
  {"id": "bo03-q033", "number": 33, "type": "fill_blank", "question": "What time will you arrive _ _ the station? – 8 pm.", "answer": "at", "audio": None},
  {"id": "bo03-q034", "number": 34, "type": "fill_blank", "question": "How long will it _ _ _ _ you to get there?", "answer": "take", "audio": None},
  {"id": "bo03-q035", "number": 35, "type": "fill_blank", "question": "Did you decide _ _ go to the zoo?", "answer": "to", "audio": None},
  {"id": "bo03-q036", "number": 36, "type": "fill_blank", "question": "Another word for “fall” is “au_ _ _ _ ”.", "answer": "tumn", "audio": None},
  {"id": "bo03-q037", "number": 37, "type": "fill_blank", "question": "Hoi An is famous _ _ _ its ancient houses.", "answer": "for", "audio": None},
  {"id": "bo03-q038", "number": 38, "type": "image_fill", "question": "In Britain, students have to wear _ _ _ _ _ _ _ _ when they go to school.", "answer": "uniforms", "audio": None},
  {"id": "bo03-q039", "number": 39, "type": "image_multiple_choice", "question": "The children are playing … in the park.", "options": ["catch", "blind man’s bluff", "hide-and-seek", "marbles"], "answer": "catch", "audio": None},
  {"id": "bo03-q040", "number": 40, "type": "odd_one_out", "question": "Odd one out:", "options": ["doing", "reading", "interesting", "writing"], "answer": "interesting", "audio": None},
  {"id": "bo03-q041", "number": 41, "type": "fill_blank", "question": "I know that he is working in the library _ _ this moment.", "answer": "at", "audio": None},
  {"id": "bo03-q042", "number": 42, "type": "word_order", "question": "out of/ onto the floor./ slipped/ The dish/ my hand/", "answer": "The dish slipped out of my hand onto the floor.", "audio": None},
  {"id": "bo03-q043", "number": 43, "type": "listening_multiple_choice", "question": "Where did neighbours gather after dinner? - ....", "options": ["Both inside and outside the TV owners’ houses", "Both inside and outside the neighbours’ houses", "Only outside the house", "Only inside the house"], "answer": "Both inside and outside the TV owners’ houses", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302333020106394_Audio.mp3"},
  {"id": "bo03-q044", "number": 44, "type": "fill_blank", "question": "SEME_ TER", "answer": "S", "audio": None},
  {"id": "bo03-q045", "number": 45, "type": "multiple_choice", "question": "It says on her report that she ... 40 kilos.", "options": ["is", "weigh", "weighs", "weight"], "answer": "weighs", "audio": None},
  {"id": "bo03-q046", "number": 46, "type": "fill_blank", "question": "Our rooms are _ _ the third floor.", "answer": "on", "audio": None},
  {"id": "bo03-q047", "number": 47, "type": "word_order", "question": "a blue/ wear/ She is going to/ dress/ at her sister’s wedding/", "answer": "She is going to wear a blue dress at her sister’s wedding", "audio": None},
  {"id": "bo03-q048", "number": 48, "type": "listening_fill", "question": "The best thing is never to start any bad _ _ _ _ _ _ .", "answer": "habits", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241439871654305_Audio.mp3"},
  {"id": "bo03-q049", "number": 49, "type": "image_fill", "question": "We don’t have much time to come back home so we go to the food _ _ _ _ l for lunch.", "answer": "stal", "audio": None},
  {"id": "bo03-q050", "number": 50, "type": "fill_blank", "question": "You should be ca_ _ _ _ l when driving.", "answer": "refu", "audio": None},
  {"id": "bo03-q051", "number": 51, "type": "word_order", "question": "decide/ You/ alone should/ for you./ what is right/", "answer": "You alone should decide what is right for you.", "audio": None},
  {"id": "bo03-q052", "number": 52, "type": "multiple_choice", "question": "How often do you jog? – ....", "options": ["Three times a week", "Third time a week", "Third times a week", "Three time a week"], "answer": "Three times a week", "audio": None},
  {"id": "bo03-q053", "number": 53, "type": "word_order", "question": "My teacher/ to take/ me/ this exam./ encouraged/", "answer": "My teacher encouraged me to take this exam.", "audio": None},
  {"id": "bo03-q054", "number": 54, "type": "word_order", "question": "in beautiful/ school uniforms./ at the festival were/ All the teachers/ and students/", "answer": "All the teachers and students at the festival were in beautiful school uniforms.", "audio": None},
  {"id": "bo03-q055", "number": 55, "type": "word_order", "question": "back to/ told him/ to go/ The teacher/ the library./", "answer": "The teacher told him to go back to the library.", "audio": None},
  {"id": "bo03-q056", "number": 56, "type": "word_order", "question": "What/ a/ beautiful/ she has!/ hat/", "answer": "What a beautiful hat she has!", "audio": None},
  {"id": "bo03-q057", "number": 57, "type": "multiple_choice", "question": "... with fire. It’s dangerous.", "options": ["Playing not", "Not to play", "To not play", "Don’t play"], "answer": "Don’t play", "audio": None},
  {"id": "bo03-q058", "number": 58, "type": "word_order", "question": "These shops/ have goods/ at reasonable/ prices./ for sale/", "answer": "These shops have goods for sale at reasonable prices.", "audio": None},
  {"id": "bo03-q059", "number": 59, "type": "listening_fill", "question": "It is not fair to _ _ _ _ _ _ _ someone just because they don’t look like you want them to look.", "answer": "dislike", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241438408526435_Audio.mp3"},
  {"id": "bo03-q060", "number": 60, "type": "multiple_choice", "question": "Did someone help you draw the picture? – No, I did it ….", "options": ["with me", "myself", "by me", "for me"], "answer": "myself", "audio": None},
  {"id": "bo03-q061", "number": 61, "type": "word_order", "question": "there/ any/ birds/ Are/ on the tree?/", "answer": "Are there any birds on the tree?", "audio": None},
  {"id": "bo03-q062", "number": 62, "type": "word_order", "question": "at midnight/ was/ ringing/ The phone/ last Sunday./", "answer": "The phone was ringing at midnight last Sunday.", "audio": None},
  {"id": "bo03-q063", "number": 63, "type": "fill_blank", "question": "Paul Anka both plays the piano _ _ _ composes music.", "answer": "and", "audio": None},
  {"id": "bo03-q064", "number": 64, "type": "fill_blank", "question": "How _ _ _ _ did he give you? - He gave me 20 dollars.", "answer": "much", "audio": None},
  {"id": "bo03-q065", "number": 65, "type": "multiple_choice", "question": "Tom has had no accidents this year. He drives the … of all.", "options": ["most carefully", "more carefully", "most careful", "more careful"], "answer": "most carefully", "audio": None},
  {"id": "bo03-q066", "number": 66, "type": "multiple_choice", "question": "’’What do you intend to do this weekend?’’ also means ’’...’’.", "options": ["What do you do this weekend?", "What are you going to do this weekend?", "What has you do this weekend?", "What are you doing this weekend?"], "answer": "What are you going to do this weekend?", "audio": None},
  {"id": "bo03-q067", "number": 67, "type": "fill_blank", "question": "What’s wrong with _ _ _ ? – I’m not feeling well.", "answer": "you", "audio": None},
  {"id": "bo03-q068", "number": 68, "type": "fill_blank", "question": "_ _ _ _ _ _ _ _ a foreign language well is a long process.", "answer": "learning", "audio": None},
  {"id": "bo03-q069", "number": 69, "type": "word_order", "question": "quiet./ is large/ near my house/ and/ The park/", "answer": "The park near my house is large and quiet.", "audio": None},
  {"id": "bo03-q070", "number": 70, "type": "fill_blank", "question": "Her _ _ _ _ of birth is on July 2nd.", "answer": "date", "audio": None},
  {"id": "bo03-q071", "number": 71, "type": "fill_blank", "question": "Do you need to use a very sharp _ _ _ _ _ to cut the flower?", "answer": "knife", "audio": None},
  {"id": "bo03-q072", "number": 72, "type": "multiple_choice", "question": "Please keep ... the grass. You shouldn’t walk on it.", "options": ["of", "off", "up", "with"], "answer": "off", "audio": None},
  {"id": "bo03-q073", "number": 73, "type": "multiple_choice", "question": "The girl you … yesterday is waiting for you in the drawing room.", "options": ["told me", "told me about", "told about", "told me about her"], "answer": "told me about", "audio": None},
  {"id": "bo03-q074", "number": 74, "type": "multiple_choice", "question": "It is very hot in our village in June. “It” here means ....", "options": ["the weather", "June", "our village", "all are correct"], "answer": "the weather", "audio": None},
  {"id": "bo03-q075", "number": 75, "type": "word_order", "question": "Jessica can/ she can’t sing/ speak English/ well but/ English songs./", "answer": "Jessica can speak English well but she can’t sing English songs.", "audio": None},
  {"id": "bo03-q076", "number": 76, "type": "listening_fill", "question": "I apologize if I hurt your _ _ _ _ _ _ _ _ .", "answer": "feelings", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2019-2020/Tinh_Thanhpho/L7/nghe/de1/6.mp3"},
  {"id": "bo03-q077", "number": 77, "type": "word_order", "question": "is a singer./ My/ younger/ sister/ Janet/", "answer": "My younger sister Janet is a singer.", "audio": None},
  {"id": "bo03-q078", "number": 78, "type": "word_order", "question": "eat food/ during/ the class./ mustn’t/ You/", "answer": "You mustn’t eat food during the class.", "audio": None},
  {"id": "bo03-q079", "number": 79, "type": "word_order", "question": "4 million/ More than/ New York/ people visit/ every year./", "answer": "More than 4 million people visit New York every year.", "audio": None},
  {"id": "bo03-q080", "number": 80, "type": "fill_blank", "question": "How _ _ _ _ _ do you visit your grandparents, Tien? – Every month.", "answer": "often", "audio": None},
  {"id": "bo03-q081", "number": 81, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["study", "sky", "why", "recycle"], "answer": "study", "audio": None},
  {"id": "bo03-q082", "number": 82, "type": "listening_fill", "question": "Did you ever _ _ _ _ _ _ why certain people do become your good friends?", "answer": "wonder", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/2/23/636865181187672729_Audio.mp3"},
  {"id": "bo03-q083", "number": 83, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["The sun is shining. What a sunny day!", "The sun is shining. What a wonderful day!", "The bird is singing. What a beautiful day!", "The sun is shining. What a beautiful day!"], "answer": "The sun is shining. What a beautiful day!", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302357786241893_Audio.mp3"},
  {"id": "bo03-q084", "number": 84, "type": "multiple_choice", "question": "Would you like some pizza, Alice? – No. .... I’m full. Thanks.", "options": ["I wouldn’t", "I don’t", "I’m not", "I don’t like"], "answer": "I wouldn’t", "audio": None},
  {"id": "bo03-q085", "number": 85, "type": "multiple_choice", "question": "Do they have to wear school uniforms … Monday … Friday?", "options": ["on/on", "at/at", "from / to", "to/from"], "answer": "from / to", "audio": None},
  {"id": "bo03-q086", "number": 86, "type": "multiple_choice", "question": "We say “... a common cold”.", "options": ["take", "catch", "do", "receive"], "answer": "catch", "audio": None},
  {"id": "bo03-q087", "number": 87, "type": "fill_blank", "question": "We should wash our hands _ _ _ _ _ _ meals.", "answer": "before", "audio": None},
  {"id": "bo03-q088", "number": 88, "type": "fill_blank", "question": "My younger sister is cooking in _ _ _ kitchen. She isn’t upstairs.", "answer": "the", "audio": None},
  {"id": "bo03-q089", "number": 89, "type": "fill_blank", "question": "She is not the kind of _ _ _ _ _ y person. She likes lying in bed and reading books.", "answer": "sport", "audio": None},
  {"id": "bo03-q090", "number": 90, "type": "multiple_choice", "question": "Are you ...? – Yes, I am.", "options": ["the French", "France", "a France", "French"], "answer": "French", "audio": None},
  {"id": "bo03-q091", "number": 91, "type": "multiple_choice", "question": "… … your father … to work every day?", "options": ["What / does/ go", "How / does / travel", "Why / do / go", "Where / do / travels"], "answer": "How / does / travel", "audio": None},
  {"id": "bo03-q092", "number": 92, "type": "fill_blank", "question": "He loves _ _ _ _ _ _ _ _ _ _ stamps. He has hundreds of stamps in his collection.", "answer": "collecting", "audio": None},
  {"id": "bo03-q093", "number": 93, "type": "listening_fill", "question": "Will you help me _ _ _ _ this desk?", "answer": "move", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2019-2020/Tinh_Thanhpho/L7/nghe/de1/3.mp3"},
  {"id": "bo03-q094", "number": 94, "type": "listening_fill", "question": "Pat buys Bill a big pad of _ _ _ _ _ .", "answer": "paper", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/12/6/635219400432714610_Audio.mp3"},
  {"id": "bo03-q095", "number": 95, "type": "listening_multiple_choice", "question": "What must he do? - ....", "options": ["Lock behind door", "Lock the left-side door", "Lock the front door", "Lock the right-side door"], "answer": "Lock the front door", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302348579105722_Audio.mp3"},
  {"id": "bo03-q096", "number": 96, "type": "multiple_choice", "question": "When the weather becomes hot, we often feel …", "options": ["hungry", "thirsty", "hungrily", "thirstily"], "answer": "thirsty", "audio": None},
  {"id": "bo03-q097", "number": 97, "type": "image_fill", "question": "I learn how to play _ _ _ _ _ r at the school club.", "answer": "guita", "audio": None},
  {"id": "bo03-q098", "number": 98, "type": "word_order", "question": "awful/ house!/ What/ an/", "answer": "What an awful house!", "audio": None},
  {"id": "bo03-q099", "number": 99, "type": "image_fill", "question": "From nine in the morning until four afternoon, Mr. Vu works in the _ _ _ _ _ with his son.", "answer": "field", "audio": None},
  {"id": "bo03-q100", "number": 100, "type": "listening_multiple_choice", "question": "Why didn’t she go with him? - ....", "options": ["Because she didn’t like him", "Because he was calling her", "Because she was waiting for a phone call", "Because she was waiting for her boyfriend"], "answer": "Because she was waiting for a phone call", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/27/635211583017394780_Audio.mp3"},
  {"id": "bo03-q101", "number": 101, "type": "fill_blank", "question": "Have a won_ _ _ ful trip and drive carefully!", "answer": "der", "audio": None},
  {"id": "bo03-q102", "number": 102, "type": "fill_blank", "question": "Does she always have lunch _ _ _ _ her friends?", "answer": "with", "audio": None},
  {"id": "bo03-q103", "number": 103, "type": "multiple_choice", "question": "Who works ...? – Clara does.", "options": ["hardest", "hard more", "harder", "more hard"], "answer": "harder", "audio": None},
  {"id": "bo03-q104", "number": 104, "type": "word_order", "question": "in/ the fall./ They sometimes/ sailing/ go/", "answer": "They sometimes go sailing in the fall.", "audio": None},
  {"id": "bo03-q105", "number": 105, "type": "fill_blank", "question": "Your application must be made _ _ _ _ 3 copies for handling by our company.", "answer": "into", "audio": None},
  {"id": "bo03-q106", "number": 106, "type": "multiple_choice", "question": "I don’t have ... rulers, but I have ... erasers.", "options": ["any / some", "some / any", "a little / any", "some / a little"], "answer": "any / some", "audio": None},
  {"id": "bo03-q107", "number": 107, "type": "multiple_choice", "question": "We collect waste food and … it to pigs.", "options": ["eat", "make", "feed", "bring"], "answer": "feed", "audio": None},
  {"id": "bo03-q108", "number": 108, "type": "multiple_choice", "question": "Is there anything good … TV tonight?", "options": ["on", "in", "near", "at"], "answer": "on", "audio": None},
  {"id": "bo03-q109", "number": 109, "type": "word_order", "question": "weekends./ often/ watches/ She/ comedies at/", "answer": "She often watches comedies at weekends.", "audio": None},
  {"id": "bo03-q110", "number": 110, "type": "word_order", "question": "pollution./ bicycles more/ reduce air/ Using/ helps/", "answer": "Using bicycles more helps reduce air pollution.", "audio": None},
  {"id": "bo03-q111", "number": 111, "type": "fill_blank", "question": "My dad _ _ _ _ times goes jogging when he has free time.", "answer": "some", "audio": None},
  {"id": "bo03-q112", "number": 112, "type": "image_fill", "question": "Hoa set the table with plates, _ _ _ _ s, chopsticks, spoon and glasses.", "answer": "bowl", "audio": None},
  {"id": "bo03-q113", "number": 113, "type": "listening_fill", "question": "My grandmother only _ _ _ _ _ _ _ us during the summer.", "answer": "visited", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241443156665162_Audio.mp3"},
  {"id": "bo03-q114", "number": 114, "type": "multiple_choice", "question": "Everybody in both cars … injured in the accident last night.", "options": ["is", "are", "was", "were"], "answer": "was", "audio": None},
  {"id": "bo03-q115", "number": 115, "type": "fill_blank", "question": "It rained a _ _ _ in Chicago last week.", "answer": "lot", "audio": None},
  {"id": "bo03-q116", "number": 116, "type": "fill_blank", "question": "My aunt tells us a lot _ _ _ _ _ you.", "answer": "about", "audio": None},
  {"id": "bo03-q117", "number": 117, "type": "multiple_choice", "question": "In Vietnam, students … to wear uniforms at school.", "options": ["want", "have", "ought", "need"], "answer": "have", "audio": None},
  {"id": "bo03-q118", "number": 118, "type": "multiple_choice", "question": "Bill has spent … the money that his father gave last week.", "options": ["most", "most of", "much", "many"], "answer": "most of", "audio": None},
  {"id": "bo03-q119", "number": 119, "type": "word_order", "question": "tonight./ the/ cat/ some milk/ Please give/", "answer": "Please give the cat some milk tonight.", "audio": None},
  {"id": "bo03-q120", "number": 120, "type": "fill_blank", "question": "_ _ careful when you cross this road!", "answer": "be", "audio": None},
  {"id": "bo03-q121", "number": 121, "type": "multiple_choice", "question": "How did you come back from the school festival …?", "options": ["last night", "tomorrow", "now", "today"], "answer": "last night", "audio": None},
  {"id": "bo03-q122", "number": 122, "type": "fill_blank", "question": "Monday is the _ _ _ _ _ day of a week.", "answer": "first", "audio": None},
  {"id": "bo03-q123", "number": 123, "type": "word_order", "question": "There will/ country in the/ near future./ be more elderly/ people in our/", "answer": "There will be more elderly people in our country in the near future.", "audio": None},
  {"id": "bo03-q124", "number": 124, "type": "multiple_choice", "question": "All of us ... students of Rose University last years.", "options": ["was", "were", "had", "are"], "answer": "were", "audio": None},
  {"id": "bo03-q125", "number": 125, "type": "fill_blank", "question": "LE_ SURE", "answer": "I", "audio": None},
  {"id": "bo03-q126", "number": 126, "type": "listening_fill", "question": "What is it that _ _ _ _ _ somebody your friend?", "answer": "makes", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241440270561226_Audio.mp3"},
  {"id": "bo03-q127", "number": 127, "type": "fill_blank", "question": "How _ _ _ _ _ do you visit your grandparents, Tien? – Every month.", "answer": "often", "audio": None},
  {"id": "bo03-q128", "number": 128, "type": "word_order", "question": "The/ on this/ rack are/ in English./ magazines/", "answer": "The magazines on this rack are in English.", "audio": None},
  {"id": "bo03-q129", "number": 129, "type": "fill_blank", "question": "My sister is one meter 45 _ _ _ _ _ meters tall.", "answer": "centi", "audio": None},
  {"id": "bo03-q130", "number": 130, "type": "multiple_choice", "question": "She is thirsty. It also means ’’She wants ....’’", "options": ["a drink", "some meat", "some potatoes", "some bread"], "answer": "a drink", "audio": None},
  {"id": "bo03-q131", "number": 131, "type": "word_order", "question": "alone./ stay at home/ The baby is/ too/ young to/", "answer": "The baby is too young to stay at home alone.", "audio": None},
  {"id": "bo03-q132", "number": 132, "type": "multiple_choice", "question": "Mr. Green bought a(n) … so that he could send or receive documents by it.", "options": ["fax machine", "public phone", "answering machine", "copier"], "answer": "fax machine", "audio": None},
  {"id": "bo03-q133", "number": 133, "type": "word_order", "question": "laugh at/ The/ his joke./ audience/ didn’t/", "answer": "The audience didn’t laugh at his joke.", "audio": None},
  {"id": "bo03-q134", "number": 134, "type": "word_order", "question": "Did she/ how to/ teach you/ new word?/ pronounce this/", "answer": "Did she teach you how to pronounce this new word?", "audio": None},
  {"id": "bo03-q135", "number": 135, "type": "fill_blank", "question": "Nam studies very well. He sings beautifully, _ _ _ .", "answer": "too", "audio": None},
  {"id": "bo03-q136", "number": 136, "type": "multiple_choice", "question": "Which is the correct spelling?", "options": ["Septembor", "September", "Sectembor", "Setember"], "answer": "September", "audio": None},
  {"id": "bo03-q137", "number": 137, "type": "listening_multiple_choice", "question": "We listen to songs and noises with our ....", "options": ["eyes", "nose", "mouth", "ears"], "answer": "ears", "audio": None},
  {"id": "bo03-q138", "number": 138, "type": "image_multiple_choice", "question": "My father likes … our household appliances.", "options": ["making", "cleaning", "washing", "repairing"], "answer": "repairing", "audio": None},
  {"id": "bo03-q139", "number": 139, "type": "fill_blank", "question": "I’m glad _ _ hear you’re well.", "answer": "to", "audio": None},
  {"id": "bo03-q140", "number": 140, "type": "fill_blank", "question": "They always go to Nevada _ _ vacation.", "answer": "on", "audio": None},
  {"id": "bo03-q141", "number": 141, "type": "fill_blank", "question": "Don’t eat too _ _ _ _ candy and sugar.", "answer": "much", "audio": None},
  {"id": "bo03-q142", "number": 142, "type": "word_order", "question": "for/ dinner/ her family./ Trinh/ usually/ cooks/", "answer": "Trinh usually cooks dinner for her family.", "audio": None},
  {"id": "bo03-q143", "number": 143, "type": "listening_multiple_choice", "question": "Who washes the dishes every night? - ....", "options": ["His brother", "His mother", "His father", "His sister"], "answer": "His mother", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/1/9/635563971134393779_Audio.mp3"},
  {"id": "bo03-q144", "number": 144, "type": "image_fill", "question": "He can’t _ _ _ _ because of his deafness.", "answer": "hear", "audio": None},
  {"id": "bo03-q145", "number": 145, "type": "fill_blank", "question": "Chau, Chi and Ngoan are my friends. We a_ _ love cooking.", "answer": "ll", "audio": None},
  {"id": "bo03-q146", "number": 146, "type": "fill_blank", "question": "Brush your teeth _ _ fore you go to bed!", "answer": "be", "audio": None},
  {"id": "bo03-q147", "number": 147, "type": "listening_multiple_choice", "question": "What do most banks and stores have? - ....", "options": ["Video cameras", "Video players", "Sound recorders", "Printers"], "answer": "Video cameras", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/3/6/635612600363095109_Audio.mp3"},
  {"id": "bo03-q148", "number": 148, "type": "multiple_choice", "question": "Are ... any pictures in your house?", "options": ["there", "this", "that", "those"], "answer": "there", "audio": None},
  {"id": "bo03-q149", "number": 149, "type": "fill_blank", "question": "MATERI_ L", "answer": "A", "audio": None},
  {"id": "bo03-q150", "number": 150, "type": "multiple_choice", "question": "... call her later. She’s not home now.", "options": ["Please", "Have", "Do", "Is"], "answer": "Please", "audio": None},
  {"id": "bo03-q151", "number": 151, "type": "multiple_choice", "question": "Would you like a drink? – Yes, please.", "options": ["What drinks do you like?", "Do you would like a drink?", "Which drinks do you like?", "Would you like a drink?"], "answer": "Would you like a drink?", "audio": None},
  {"id": "bo03-q152", "number": 152, "type": "multiple_choice", "question": "My new glasses cost me … the last pair that I bought.", "options": ["three times as much as", "as much three times as", "three times more", "times three"], "answer": "three times as much as", "audio": None},
  {"id": "bo03-q153", "number": 153, "type": "word_order", "question": "make a/ call/ Can I/ on your/ mobile phone?/", "answer": "Can I make a call on your mobile phone?", "audio": None},
  {"id": "bo03-q154", "number": 154, "type": "image_fill", "question": "It’s no use advising him to stop _ _ _ _ _ _ _ .", "answer": "smoking", "audio": None},
  {"id": "bo03-q155", "number": 155, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently from the others:", "options": ["cloudy", "house", "about", "four"], "answer": "four", "audio": None},
  {"id": "bo03-q156", "number": 156, "type": "multiple_choice", "question": "I don’t have ... rulers, but I have ... erasers.", "options": ["any / some", "some / any", "a little / any", "some / a little"], "answer": "any / some", "audio": None},
  {"id": "bo03-q157", "number": 157, "type": "word_order", "question": "your homework/ before/ going to bed./ must do/ You/", "answer": "You must do your homework before going to bed.", "audio": None},
  {"id": "bo03-q158", "number": 158, "type": "multiple_choice", "question": "Which sentence is correct?", "options": ["Their cars are front of the station.", "Their cars are in front of the station.", "Theirs cars are in front the station.", "Their cars in front of the station."], "answer": "Their cars are in front of the station.", "audio": None},
  {"id": "bo03-q159", "number": 159, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["Sometimes the noise affects me at night.", "Sometimes the noise keeps me awake at night.", "Sometimes the noise helps me awake at night.", "Sometimes the noise keeps awake me at night."], "answer": "Sometimes the noise keeps me awake at night.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302360119537992_Audio.mp3"},
  {"id": "bo03-q160", "number": 160, "type": "image_multiple_choice", "question": "Look at the picture. Which sentence is correct?", "options": ["The red ball is on the ground.", "The black and white ball is on the grass.", "The black and white ball is rolling.", "The pink ball is on the floor."], "answer": "The black and white ball is on the grass.", "audio": None},
  {"id": "bo03-q161", "number": 161, "type": "multiple_choice", "question": "… Could you show me how to get the nearest post office?", "options": ["Stop.", "Excuse me?", "Have a nice day.", "There, there."], "answer": "Excuse me?", "audio": None},
  {"id": "bo03-q162", "number": 162, "type": "fill_blank", "question": "_ _ _ _ are they? - They are rulers and books.", "answer": "what", "audio": None},
  {"id": "bo03-q163", "number": 163, "type": "fill_blank", "question": "Victoria is always worried _ _ _ _ _ the safety of her family.", "answer": "about", "audio": None},
  {"id": "bo03-q164", "number": 164, "type": "multiple_choice", "question": "The manager told me … harder.", "options": ["work", "working", "to work", "worked"], "answer": "to work", "audio": None},
  {"id": "bo03-q165", "number": 165, "type": "multiple_choice", "question": "If you don’t need the light, ... it ....", "options": ["turn off", "turn on", "turn / of", "turn up"], "answer": "turn off", "audio": None},
  {"id": "bo03-q166", "number": 166, "type": "multiple_choice", "question": "She always … her appearance before going out.", "options": ["cares for", "looks for", "takes feeling in", "takes pride in"], "answer": "cares for", "audio": None},
  {"id": "bo03-q167", "number": 167, "type": "multiple_choice", "question": "He was absent from work because ... illness.", "options": ["the", "an", "for", "of"], "answer": "of", "audio": None},
  {"id": "bo03-q168", "number": 168, "type": "word_order", "question": "2015./ Today/ April/ 11th of/ is/", "answer": "Today is 11th of April 2015.", "audio": None},
  {"id": "bo03-q169", "number": 169, "type": "word_order", "question": "kitchen./ from the/ of food/ good smell/ There is a/", "answer": "There is a good smell of food from the kitchen.", "audio": None},
  {"id": "bo03-q170", "number": 170, "type": "listening_fill", "question": "Would you _ _ _ _ taking us a photo?", "answer": "mind", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/27/635211588037951598_Audio.mp3"},
  {"id": "bo03-q171", "number": 171, "type": "word_order", "question": "called/ newspaper delivery./ her/ Mrs. Lan/ about/", "answer": "Mrs. Lan called about her newspaper delivery.", "audio": None},
  {"id": "bo03-q172", "number": 172, "type": "fill_blank", "question": "RE_ IEW", "answer": "V", "audio": None},
  {"id": "bo03-q173", "number": 173, "type": "fill_blank", "question": "Mr. Pike didn’t go to work yesterday _ _ _ _ _ _ _ of his sickness.", "answer": "because", "audio": None},
  {"id": "bo03-q174", "number": 174, "type": "word_order", "question": "knife!/ careful/ that/ with/ Be/", "answer": "Be careful with that knife!", "audio": None},
  {"id": "bo03-q175", "number": 175, "type": "word_order", "question": "coffee?/ to make/ Would you/ like me/ some/", "answer": "Would you like me to make some coffee?", "audio": None},
  {"id": "bo03-q176", "number": 176, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["The village has quite a little traffic.", "The village was quiet with a little traffic.", "The village was tired and there was only a little traffic.", "The village was quiet but there was a lot of traffic."], "answer": "The village was quiet with a little traffic.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302358646739405_Audio.mp3"},
  {"id": "bo03-q177", "number": 177, "type": "word_order", "question": "Hanoi twice/ a week/ for business./ This man/ travels to/", "answer": "This man travels to Hanoi twice a week for business.", "audio": None},
  {"id": "bo03-q178", "number": 178, "type": "listening_fill", "question": "A good gift doesn’t have to be something that _ _ _ _ _ a lot.", "answer": "costs", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241545240766707_Audio.mp3"},
  {"id": "bo03-q179", "number": 179, "type": "multiple_choice", "question": "Which sentence is correct?", "options": ["They sat all down to eat.", "They sat down to all eat.", "They all sat down to eat.", "All they sat down to eat."], "answer": "They all sat down to eat.", "audio": None},
  {"id": "bo03-q180", "number": 180, "type": "fill_blank", "question": "She _ _ _ _ _ _ _ many of her old friends to her birthday party on Saturday.", "answer": "invited", "audio": None},
  {"id": "bo03-q181", "number": 181, "type": "multiple_choice", "question": "His father had some … problems two months ago.", "options": ["health", "healthy", "healthily", "unhealthy"], "answer": "health", "audio": None},
  {"id": "bo03-q182", "number": 182, "type": "multiple_choice", "question": "What about spinach and carrots? – Ok, let’s get ... of those.", "options": ["some", "few", "any", "many"], "answer": "some", "audio": None},
  {"id": "bo03-q183", "number": 183, "type": "word_order", "question": "move/ We/ going to/ our house this month./ are/", "answer": "We are going to move our house this month.", "audio": None},
  {"id": "bo03-q184", "number": 184, "type": "fill_blank", "question": "I’m from Great Britain. I’m Bri_ _ _ _ .", "answer": "tish", "audio": None},
  {"id": "bo03-q185", "number": 185, "type": "word_order", "question": "better at/ in my class is/ than Thu./ Literature/ No one/", "answer": "No one in my class is better at Literature than Thu.", "audio": None},
  {"id": "bo03-q186", "number": 186, "type": "multiple_choice", "question": "Her bag is overweight. It means her bag is ....", "options": ["light", "too heavy", "strong", "weak"], "answer": "too heavy", "audio": None},
  {"id": "bo03-q187", "number": 187, "type": "word_order", "question": "and fishing./ an ideal place/ The lake is/ for us/ to go swimming/", "answer": "The lake is an ideal place for us to go swimming and fishing.", "audio": None},
  {"id": "bo03-q188", "number": 188, "type": "word_order", "question": "more/ novels,/ actions./ Unlike the/ films show/", "answer": "Unlike the novels, films show more actions.", "audio": None},
  {"id": "bo03-q189", "number": 189, "type": "word_order", "question": "last/ Was/ the club/ crowded/ Friday night?/", "answer": "Was the club crowded last Friday night?", "audio": None},
  {"id": "bo03-q190", "number": 190, "type": "image_fill", "question": "Tom: What colour is her hair? - Jane: It’s _ _ _ .", "answer": "red", "audio": None},
  {"id": "bo03-q191", "number": 191, "type": "fill_blank", "question": "I can’t imagine how beautiful you _ _ _ now.", "answer": "are", "audio": None},
  {"id": "bo03-q192", "number": 192, "type": "word_order", "question": "late/ for the meeting./ Hurry up/ you will be/ or/", "answer": "Hurry up or you will be late for the meeting.", "audio": None},
  {"id": "bo03-q193", "number": 193, "type": "fill_blank", "question": "I can’t use the washing machine. Can you _ _ _ it?", "answer": "fix", "audio": None},
  {"id": "bo03-q194", "number": 194, "type": "image_fill", "question": "Jane likes to wear colourful _ _ _ _ _ _ _ .", "answer": "clothes", "audio": None},
  {"id": "bo03-q195", "number": 195, "type": "multiple_choice", "question": "Snow appears when the weather is very ....", "options": ["hot", "warm", "ice", "cold"], "answer": "cold", "audio": None},
  {"id": "bo03-q196", "number": 196, "type": "multiple_choice", "question": "Jakes wakes up ....", "options": ["early morning", "early in morning", "the early morning", "early in the morning"], "answer": "early in the morning", "audio": None},
  {"id": "bo03-q197", "number": 197, "type": "multiple_choice", "question": "At present” has similar meaning to “...”.", "options": ["in the past", "last", "now", "next"], "answer": "now", "audio": None},
  {"id": "bo03-q198", "number": 198, "type": "multiple_choice", "question": "My cat … its face every morning.", "options": ["clears", "makes", "gets", "washes"], "answer": "washes", "audio": None},
  {"id": "bo03-q199", "number": 199, "type": "word_order", "question": "laugh./ class/ the whole/ My funny/ story made/", "answer": "My funny story made the whole class laugh.", "audio": None},
  {"id": "bo03-q200", "number": 200, "type": "fill_blank", "question": "Your English is much better _ _ _ _ mine.", "answer": "than", "audio": None}
]

def get_bo03():
    questions = [normalize_question(q, 3) for q in raw_questions]
    return {
        "examId": "03",
        "setId": "bo03",
        "title": "IOE K7 2024-2025 - Đề số 03",
        "totalQuestions": len(questions),
        "questions": questions
    }
