# Raw questions for bo04
import json
from normalizer import normalize_question

raw_questions = [
  {"id": "bo04-q001", "number": 1, "type": "fill_blank", "question": "Tuan _ _ tall and handsome with a smiling face.", "answer": "is", "audio": None},
  {"id": "bo04-q002", "number": 2, "type": "word_order", "question": "some/ There are/ behind/ tall trees/ my house./", "answer": "There are some tall trees behind my house.", "audio": None},
  {"id": "bo04-q003", "number": 3, "type": "fill_blank", "question": "You will _ _ fine after taking these medicines.", "answer": "be", "audio": None},
  {"id": "bo04-q004", "number": 4, "type": "word_order", "question": "for the/ dictionary?/ Does she/ money/ need some/", "answer": "Does she need some money for the dictionary?", "audio": None},
  {"id": "bo04-q005", "number": 5, "type": "fill_blank", "question": "I’m glad to hear you _ _ _ doing well.", "answer": "are", "audio": None},
  {"id": "bo04-q006", "number": 6, "type": "word_order", "question": "I will call/ me/ the police if/ alone./ you don’t leave/", "answer": "I will call the police if you don’t leave me alone.", "audio": None},
  {"id": "bo04-q007", "number": 7, "type": "word_order", "question": "pleased that/ I am/ are well./ your family/ you and/", "answer": "I am pleased that you and your family are well.", "audio": None},
  {"id": "bo04-q008", "number": 8, "type": "listening_fill", "question": "She doesn’t usually come home _ _ _ _ _ 10 o’clock.", "answer": "until", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/1/8/635563332654623107_Audio.mp3"},
  {"id": "bo04-q009", "number": 9, "type": "fill_blank", "question": "The secretary took a message _ _ her boss.", "answer": "to", "audio": None},
  {"id": "bo04-q010", "number": 10, "type": "fill_blank", "question": "Hoang likes playing _ _ _ piano, too.", "answer": "the", "audio": None},
  {"id": "bo04-q011", "number": 11, "type": "multiple_choice", "question": "Can’t you speak English?", "options": ["Yes. I can speak Spanish but I can’t speak English.", "Yes. I can speak English well.", "No. I can speak English well.", "No. I can speak Spanish, too."], "answer": "Yes. I can speak English well.", "audio": None},
  {"id": "bo04-q012", "number": 12, "type": "word_order", "question": "last year./ This book/ for children/ was/ written/", "answer": "This book was written for children last year.", "audio": None},
  {"id": "bo04-q013", "number": 13, "type": "fill_blank", "question": "Children should spend only a small part of their free time playing electronic _ _ _ _ _ .", "answer": "games", "audio": None},
  {"id": "bo04-q014", "number": 14, "type": "fill_blank", "question": "What was _ _ _ most common illness?", "answer": "the", "audio": None},
  {"id": "bo04-q015", "number": 15, "type": "word_order", "question": "does./ I don’t/ my sister/ hard as/ work as/", "answer": "I don’t work as hard as my sister does.", "audio": None},
  {"id": "bo04-q016", "number": 16, "type": "listening_fill", "question": "He said that he had a lot of free time because I _ _ _ _ _ _ him so much.", "answer": "helped", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241439222278003_Audio.mp3"},
  {"id": "bo04-q017", "number": 17, "type": "fill_blank", "question": "How many kilos _ _ rice do you need? – 10 kilos, please.", "answer": "of", "audio": None},
  {"id": "bo04-q018", "number": 18, "type": "multiple_choice", "question": "… time do you spend learning English every day?", "options": ["How much", "How many", "How long", "How often"], "answer": "How much", "audio": None},
  {"id": "bo04-q019", "number": 19, "type": "word_order", "question": "to apologize./ too/ late/ It is/ never/", "answer": "It is never too late to apologize.", "audio": None},
  {"id": "bo04-q020", "number": 20, "type": "stress", "question": "Which word has different stress pattern?", "options": ["uncle", "idea", "dozen", "purple"], "answer": "idea", "audio": None},
  {"id": "bo04-q021", "number": 21, "type": "fill_blank", "question": "Many people have stopped smoking _ _ _ _ _ _ _ they are afraid that it may be harmful to their health.", "answer": "because", "audio": None},
  {"id": "bo04-q022", "number": 22, "type": "fill_blank", "question": "Why does the world need more _ _ _ _ and land?", "answer": "food", "audio": None},
  {"id": "bo04-q023", "number": 23, "type": "listening_fill", "question": "We live in an _ _ _ _ _ _ _ _ _ in the city.", "answer": "apartment", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/14/635303884799291950_Audio.mp3"},
  {"id": "bo04-q024", "number": 24, "type": "multiple_choice", "question": "Do they have to wear school uniforms … Monday … Friday?", "options": ["on/on", "at/at", "from / to", "to/from"], "answer": "from / to", "audio": None},
  {"id": "bo04-q025", "number": 25, "type": "fill_blank", "question": "What’s this? - _ _ ’s a desk.", "answer": "it", "audio": None},
  {"id": "bo04-q026", "number": 26, "type": "fill_blank", "question": "My grandma is too old. She can’t _ _ _ without her glasses.", "answer": "see", "audio": None},
  {"id": "bo04-q027", "number": 27, "type": "word_order", "question": "They/ in the/ to race/ began/ forest./", "answer": "They began to race in the forest.", "audio": None},
  {"id": "bo04-q028", "number": 28, "type": "multiple_choice", "question": "Please tell me ... about your hobbies.", "options": ["many", "much", "few", "more"], "answer": "more", "audio": None},
  {"id": "bo04-q029", "number": 29, "type": "word_order", "question": "English books/ the shelf/ to/ are on/ the right./", "answer": "English books are on the shelf to the right.", "audio": None},
  {"id": "bo04-q030", "number": 30, "type": "fill_blank", "question": "What’s the weather _ _ _ _ in winter? – It’s very cold.", "answer": "like", "audio": None},
  {"id": "bo04-q031", "number": 31, "type": "word_order", "question": "playing/ the piano/ practice/ in the afternoon?/ Do they often/", "answer": "Do they often practice playing the piano in the afternoon?", "audio": None},
  {"id": "bo04-q032", "number": 32, "type": "multiple_choice", "question": "What is her …? – She is Australian.", "options": ["language", "nationality", "country", "city"], "answer": "nationality", "audio": None},
  {"id": "bo04-q033", "number": 33, "type": "multiple_choice", "question": "We feel ... when we have a stomachache.", "options": ["sneeze", "cough", "painful", "running nose"], "answer": "painful", "audio": None},
  {"id": "bo04-q034", "number": 34, "type": "word_order", "question": "the farm/ often have/ dirt on/ them./ Vegetables from/", "answer": "Vegetables from the farm often have dirt on them.", "audio": None},
  {"id": "bo04-q035", "number": 35, "type": "multiple_choice", "question": "... to keep fit and stay healthy.", "options": ["It important", "It is important", "It does important", "It’s important very"], "answer": "It is important", "audio": None},
  {"id": "bo04-q036", "number": 36, "type": "fill_blank", "question": "GO_ F", "answer": "L", "audio": None},
  {"id": "bo04-q037", "number": 37, "type": "multiple_choice", "question": "… do they go to church? - Every Sunday afternoon.", "options": ["How high", "How many", "How much", "How often"], "answer": "How often", "audio": None},
  {"id": "bo04-q038", "number": 38, "type": "fill_blank", "question": "Could you _ _ _ _ me where the post office is?", "answer": "show", "audio": None},
  {"id": "bo04-q039", "number": 39, "type": "fill_blank", "question": "W_ ATEVER", "answer": "H", "audio": None},
  {"id": "bo04-q040", "number": 40, "type": "word_order", "question": "you/ some money?/ lend/ Would/ me/", "answer": "Would you lend me some money?", "audio": None},
  {"id": "bo04-q041", "number": 41, "type": "fill_blank", "question": "Thanks a _ _ _ ! – You’re welcome!", "answer": "lot", "audio": None},
  {"id": "bo04-q042", "number": 42, "type": "word_order", "question": "paddies./ This was/ saw the/ the second/ time Liz/", "answer": "This was the second time Liz saw the paddies.", "audio": None},
  {"id": "bo04-q043", "number": 43, "type": "fill_blank", "question": "_ _ _ John and his friends lazy? – No, they work very hard.", "answer": "Are", "audio": None},
  {"id": "bo04-q044", "number": 44, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["scared", "wanted", "interested", "needed"], "answer": "scared", "audio": None},
  {"id": "bo04-q045", "number": 45, "type": "multiple_choice", "question": "My school is at ….", "options": ["30 Hoang Hoa Tham Road", "Hoan Kiem District", "a village far from here", "Nam Dinh Province"], "answer": "30 Hoang Hoa Tham Road", "audio": None},
  {"id": "bo04-q046", "number": 46, "type": "fill_blank", "question": "He wants to learn _ _ _ to use the computer.", "answer": "how", "audio": None},
  {"id": "bo04-q047", "number": 47, "type": "listening_multiple_choice", "question": "What could man do after the invention of breathing equipment? - ....", "options": ["Man could breathe freely underwater", "Man could swim freely undersea", "Man could swim freely underwater", "Man could breathe freely in the swimming pool"], "answer": "Man could swim freely underwater", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302333504175244_Audio.mp3"},
  {"id": "bo04-q048", "number": 48, "type": "listening_fill", "question": "They are going to spend their _ _ _ _ _ _ _ _ in Vung Tau.", "answer": "vacation", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/1/9/635563988331724333_Audio.mp3"},
  {"id": "bo04-q049", "number": 49, "type": "fill_blank", "question": "Staying at _ _ _ _ would be better than going out tonight.", "answer": "home", "audio": None},
  {"id": "bo04-q050", "number": 50, "type": "fill_blank", "question": "Nam studies very well. He sings beautifully, _ _ _ .", "answer": "too", "audio": None},
  {"id": "bo04-q051", "number": 51, "type": "word_order", "question": "from/ the city centre./ very/ far/ John’s apartment is/", "answer": "John’s apartment is very far from the city centre.", "audio": None},
  {"id": "bo04-q052", "number": 52, "type": "fill_blank", "question": "ENTERT_ IN", "answer": "A", "audio": None},
  {"id": "bo04-q053", "number": 53, "type": "fill_blank", "question": "How _ _ _ _ did he give you? - He gave me 20 dollars.", "answer": "much", "audio": None},
  {"id": "bo04-q054", "number": 54, "type": "multiple_choice", "question": "We … everything we can to help you!", "options": ["do", "shall do", "would do", "had done"], "answer": "shall do", "audio": None},
  {"id": "bo04-q055", "number": 55, "type": "multiple_choice", "question": "I spoke very slowly … he didn’t understand English very well.", "options": ["so that", "because", "due to", "because of"], "answer": "because", "audio": None},
  {"id": "bo04-q056", "number": 56, "type": "image_fill", "question": "He can’t _ _ _ _ because of his deafness.", "answer": "hear", "audio": None},
  {"id": "bo04-q057", "number": 57, "type": "multiple_choice", "question": "What time does his class end? – At ....", "options": ["afternoon", "evening", "night", "11 AM"], "answer": "11 AM", "audio": None},
  {"id": "bo04-q058", "number": 58, "type": "multiple_choice", "question": "A pilot is the ....", "options": ["driver of an airplane", "driver of a bus", "driver of a coach", "driver of a train"], "answer": "driver of an airplane", "audio": None},
  {"id": "bo04-q059", "number": 59, "type": "fill_blank", "question": "I bought a cup of coffee and some pizzas _ _ _ lunch.", "answer": "for", "audio": None},
  {"id": "bo04-q060", "number": 60, "type": "stress", "question": "Which word is stressed on the first syllable?", "options": ["vacation", "summer", "activity", "pollute"], "answer": "summer", "audio": None},
  {"id": "bo04-q061", "number": 61, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["brother", "mother", "come", "police"], "answer": "police", "audio": None},
  {"id": "bo04-q062", "number": 62, "type": "multiple_choice", "question": "Don’t eat too much sugar. Don’t forget to do exercises, ....", "options": ["either", "neither", "too", "so"], "answer": "either", "audio": None},
  {"id": "bo04-q063", "number": 63, "type": "multiple_choice", "question": "What ... you do the last time you ... a bad toothache?", "options": ["do / had", "did / have", "did / had", "do / have"], "answer": "did / had", "audio": None},
  {"id": "bo04-q064", "number": 64, "type": "fill_blank", "question": "They are _ _ _ ing medical check-up at the moment.", "answer": "hav", "audio": None},
  {"id": "bo04-q065", "number": 65, "type": "listening_multiple_choice", "question": "What does pop music mean? - ....", "options": ["Popular music", "Unpopular music", "Poland music", "Popcorn music"], "answer": "Popular music", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/3/6/635612599647521852_Audio.mp3"},
  {"id": "bo04-q066", "number": 66, "type": "multiple_choice", "question": "He’d like a … of soap.", "options": ["bottle", "can", "tube", "bar"], "answer": "bar", "audio": None},
  {"id": "bo04-q067", "number": 67, "type": "fill_blank", "question": "_ _ _ _ is the tall building over there? - It’s a new library.", "answer": "What", "audio": None},
  {"id": "bo04-q068", "number": 68, "type": "stress", "question": "Which word has different stress pattern?", "options": ["surgery", "normal", "amount", "hygiene"], "answer": "amount", "audio": None},
  {"id": "bo04-q069", "number": 69, "type": "word_order", "question": "not/ for/ Drinking wine is/ your health./ good/", "answer": "Drinking wine is not good for your health.", "audio": None},
  {"id": "bo04-q070", "number": 70, "type": "multiple_choice", "question": "She had worked … she made herself ill.", "options": ["such hard that", "such hardly that", "so hardly that", "so hard that"], "answer": "so hard that", "audio": None},
  {"id": "bo04-q071", "number": 71, "type": "word_order", "question": "morning./ the news/ listen to/ every/ They don’t/", "answer": "They don’t listen to the news every morning.", "audio": None},
  {"id": "bo04-q072", "number": 72, "type": "listening_fill", "question": "My mother is always giving me _ _ _ _ _ _ .", "answer": "advice", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241440753690891_Audio.mp3"},
  {"id": "bo04-q073", "number": 73, "type": "listening_fill", "question": "She says that I should eat _ _ _ _ _ _ _ _ _ _ if I want to be strong when I grow up.", "answer": "vegetables", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241440659316555_Audio.mp3"},
  {"id": "bo04-q074", "number": 74, "type": "fill_blank", "question": "_ _ _ _ _ I carry that luggage for you? – Thanks.", "answer": "could", "audio": None},
  {"id": "bo04-q075", "number": 75, "type": "multiple_choice", "question": "She is lying on the beach ... the sun.", "options": ["on", "under", "above", "below"], "answer": "under", "audio": None},
  {"id": "bo04-q076", "number": 76, "type": "multiple_choice", "question": "A movie theater is also a ....", "options": ["cinema", "film", "video", "circus"], "answer": "cinema", "audio": None},
  {"id": "bo04-q077", "number": 77, "type": "word_order", "question": "play football/ school/ team?/ for our/ Does he/", "answer": "Does he play football for our school team?", "audio": None},
  {"id": "bo04-q078", "number": 78, "type": "word_order", "question": "in his/ free time./ My father/ listening to music/ enjoys/", "answer": "My father enjoys listening to music in his free time.", "audio": None},
  {"id": "bo04-q079", "number": 79, "type": "multiple_choice", "question": "He enjoys sports. It means he ... sports.", "options": ["favorite", "likes", "hates", "doesn’t like"], "answer": "likes", "audio": None},
  {"id": "bo04-q080", "number": 80, "type": "fill_blank", "question": "I have a bad cold. I keep snee_ _ _ _ .", "answer": "zing", "audio": None},
  {"id": "bo04-q081", "number": 81, "type": "word_order", "question": "Hana’s class/ were very nice/ to her./ children in/ The other/", "answer": "The other children in Hana’s class were very nice to her.", "audio": None},
  {"id": "bo04-q082", "number": 82, "type": "image_fill", "question": "I think it’s going to rain. It’s _ _ _ _ _ _ .", "answer": "cloudy", "audio": None},
  {"id": "bo04-q083", "number": 83, "type": "fill_blank", "question": "_ _ careful when you cross this road!", "answer": "be", "audio": None},
  {"id": "bo04-q084", "number": 84, "type": "odd_one_out", "question": "Odd one out:", "options": ["heavy", "height", "wide", "tall"], "answer": "height", "audio": None},
  {"id": "bo04-q085", "number": 85, "type": "multiple_choice", "question": "Oh, I don’t like pork. - ….", "options": ["I don’t like, too", "Either do I", "Neither do I", "So don’t I"], "answer": "Neither do I", "audio": None},
  {"id": "bo04-q086", "number": 86, "type": "fill_blank", "question": "Let’s put the coffee table in the middle _ _ the room.", "answer": "of", "audio": None},
  {"id": "bo04-q087", "number": 87, "type": "word_order", "question": "gallery with/ beautiful pictures./ an exciting art/ have been to/ Today I/", "answer": "Today I have been to an exciting art gallery with beautiful pictures.", "audio": None},
  {"id": "bo04-q088", "number": 88, "type": "fill_blank", "question": "She walks to school. It means she goes to school on _ _ _ _ .", "answer": "foot", "audio": None},
  {"id": "bo04-q089", "number": 89, "type": "stress", "question": "Which word has different stress pattern?", "options": ["vegetable", "intersection", "businessman", "neighborhood"], "answer": "intersection", "audio": None},
  {"id": "bo04-q090", "number": 90, "type": "image_fill", "question": "An: What’s Tommy going to do? - Tony: He is going to _ _ _ _ _ his teeth.", "answer": "brush", "audio": None},
  {"id": "bo04-q091", "number": 91, "type": "odd_one_out", "question": "Odd one out:", "options": ["at present", "at the moment", "now", "yesterday"], "answer": "yesterday", "audio": None},
  {"id": "bo04-q092", "number": 92, "type": "fill_blank", "question": "She will finish all her homework in less _ _ _ _ 2 hours.", "answer": "than", "audio": None},
  {"id": "bo04-q093", "number": 93, "type": "fill_blank", "question": "My father is a mechanic. He _ _ _ _ _ for a factory in the suburb.", "answer": "works", "audio": None},
  {"id": "bo04-q094", "number": 94, "type": "listening_fill", "question": "She _ _ _ _ _ _ her eyes and felt like a bird in the sky.", "answer": "closed", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/11/14/635515764454670408_Audio.mp3"},
  {"id": "bo04-q095", "number": 95, "type": "multiple_choice", "question": "’’…’’ has opposite meaning to ’’…’’. ", "options": ["Full / thin", "Full / low", "Full / heavy", "Full / weight"], "answer": "Full / thin", "audio": None},
  {"id": "bo04-q096", "number": 96, "type": "word_order", "question": "to walk/ The elephant/ is the largest/ animal/ on Earth./", "answer": "The elephant is the largest animal to walk on Earth.", "audio": None},
  {"id": "bo04-q097", "number": 97, "type": "multiple_choice", "question": "I am sleepy. I … go to bed early.", "options": ["must", "have to", "can", "mustn’t"], "answer": "must", "audio": None},
  {"id": "bo04-q098", "number": 98, "type": "fill_blank", "question": "In rich countries, people spend a lot of money _ _ pet food.", "answer": "on", "audio": None},
  {"id": "bo04-q099", "number": 99, "type": "image_fill", "question": "My sister has a big collection of _ _ _ _ _ _ .", "answer": "stamps", "audio": None},
  {"id": "bo04-q100", "number": 100, "type": "word_order", "question": "because he/ Mike didn’t/ go to school/ was sick./ yesterday/", "answer": "Mike didn’t go to school yesterday because he was sick.", "audio": None},
  {"id": "bo04-q101", "number": 101, "type": "word_order", "question": "two hours/ each day/ It takes her/ to do/ her homework./", "answer": "It takes her two hours each day to do her homework.", "audio": None},
  {"id": "bo04-q102", "number": 102, "type": "word_order", "question": "to/ her friends/ come./ all/ She is expecting/", "answer": "She is expecting all her friends to come.", "audio": None},
  {"id": "bo04-q103", "number": 103, "type": "listening_fill", "question": "Some people decide that they will lose weight so that they can be _ _ _ _ _ _ _ _ _ .", "answer": "healthier", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241439553841132_Audio.mp3"},
  {"id": "bo04-q104", "number": 104, "type": "multiple_choice", "question": "I think I’ll go to see ‘Shrek 2’ tomorrow. - …", "options": ["Are you?", "Can you?", "Do you?", "Will you?"], "answer": "Will you?", "audio": None},
  {"id": "bo04-q105", "number": 105, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["There were many sharks, dolphins and turtles.", "There weren’t many sharks, dolphins and turtles.", "There were some sharks, dolphins and turtles.", "There were sometimes many sharks, dolphins and turtles."], "answer": "There were many sharks, dolphins and turtles.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302360873643316_Audio.mp3"},
  {"id": "bo04-q106", "number": 106, "type": "word_order", "question": "to get used/ with/ It’s difficult/ chopsticks./ to eating/", "answer": "It’s difficult to get used to eating with chopsticks.", "audio": None},
  {"id": "bo04-q107", "number": 107, "type": "stress", "question": "Choose the word which has different stress pattern:", "options": ["unhappy", "comfortable", "expensive", "material"], "answer": "comfortable", "audio": None},
  {"id": "bo04-q108", "number": 108, "type": "listening_fill", "question": "Both Mike and his father were very _ _ _ _ _ _ _ when they read about the coming events.", "answer": "excited", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/3/6/635612563380442436_Audio.mp3"},
  {"id": "bo04-q109", "number": 109, "type": "word_order", "question": "cucumber/ favorite/ vegetables./ Spinach and/ are my/", "answer": "Spinach and cucumber are my favorite vegetables.", "audio": None},
  {"id": "bo04-q110", "number": 110, "type": "multiple_choice", "question": "Do you know what she … at the moment?", "options": ["does", "doing", "doing is", "is doing"], "answer": "is doing", "audio": None},
  {"id": "bo04-q111", "number": 111, "type": "multiple_choice", "question": "John enjoys … tennis.", "options": ["playing", "play", "played", "to play"], "answer": "playing", "audio": None},
  {"id": "bo04-q112", "number": 112, "type": "multiple_choice", "question": "It’s difficult to cross this street because there is too much … .", "options": ["crowd", "traffic", "people", "transport"], "answer": "traffic", "audio": None},
  {"id": "bo04-q113", "number": 113, "type": "fill_blank", "question": "The earth goes _ _ _ _ _ _ the sun.", "answer": "around", "audio": None},
  {"id": "bo04-q114", "number": 114, "type": "word_order", "question": "did/ subjects/ yesterday?/ Which/ you have/", "answer": "Which subjects did you have yesterday?", "audio": None},
  {"id": "bo04-q115", "number": 115, "type": "word_order", "question": "the Browns/ often go for/ Where do/ their summer/ vacation?/", "answer": "Where do the Browns often go for their summer vacation?", "audio": None},
  {"id": "bo04-q116", "number": 116, "type": "multiple_choice", "question": "… straight across the road.", "options": ["Don’t run", "Not run", "No run", "Can’t run"], "answer": "Don’t run", "audio": None},
  {"id": "bo04-q117", "number": 117, "type": "fill_blank", "question": "_ _ _ _ _ did you go last night? – Oh, I went to the cinema.", "answer": "where", "audio": None},
  {"id": "bo04-q118", "number": 118, "type": "multiple_choice", "question": "She is trying to … her work before the coming exam.", "options": ["rehearsal", "review", "practice", "study"], "answer": "review", "audio": None},
  {"id": "bo04-q119", "number": 119, "type": "word_order", "question": "tales when we/ were young./ told us fairy/ often/ My grandmother/", "answer": "My grandmother often told us fairy tales when we were young.", "audio": None},
  {"id": "bo04-q120", "number": 120, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently from the others:", "options": ["town", "flow", "now", "cow"], "answer": "flow", "audio": None},
  {"id": "bo04-q121", "number": 121, "type": "fill_blank", "question": "He never gets _ _ _ good marks because he is too lazy.", "answer": "any", "audio": None},
  {"id": "bo04-q122", "number": 122, "type": "multiple_choice", "question": "He isn’t happy because he has ... friends in Rome.", "options": ["much", "any", "few", "little"], "answer": "few", "audio": None},
  {"id": "bo04-q123", "number": 123, "type": "word_order", "question": "three/ the first/ has answered/ questions./ Each student/", "answer": "Each student has answered the first three questions.", "audio": None},
  {"id": "bo04-q124", "number": 124, "type": "fill_blank", "question": "I always try to avoid _ _ _ _ _ _ _ _ _ money from my friends.", "answer": "borrowing", "audio": None},
  {"id": "bo04-q125", "number": 125, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["fall", "pastime", "badminton", "camp"], "answer": "fall", "audio": None},
  {"id": "bo04-q126", "number": 126, "type": "multiple_choice", "question": "Her parents are pleased ... she often gets good marks.", "options": ["why", "though", "because", "which"], "answer": "because", "audio": None},
  {"id": "bo04-q127", "number": 127, "type": "word_order", "question": "the aquarium./ There are/ many different/ fish in/ types of/", "answer": "There are many different types of fish in the aquarium.", "audio": None},
  {"id": "bo04-q128", "number": 128, "type": "multiple_choice", "question": "Who are you going out ...? – Jamie and Sam.", "options": ["to", "with", "at", "from"], "answer": "with", "audio": None},
  {"id": "bo04-q129", "number": 129, "type": "listening_fill", "question": "As we were _ _ _ _ _ _ _ _ the street, we saw an accident.", "answer": "crossing", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/1/9/635563935835834218_Audio.mp3"},
  {"id": "bo04-q130", "number": 130, "type": "word_order", "question": "an ideal place/ for us/ to go swimming/ and fishing./ The lake is/", "answer": "The lake is an ideal place for us to go swimming and fishing.", "audio": None},
  {"id": "bo04-q131", "number": 131, "type": "multiple_choice", "question": "How much ... do you want, Mom?", "options": ["apples", "fish", "pears", "eggs"], "answer": "fish", "audio": None},
  {"id": "bo04-q132", "number": 132, "type": "multiple_choice", "question": "We bought ... as souvenirs for our parents.", "options": ["all kinds of stamp", "all kind of stamp", "all kind of stamps", "all kinds of stamps"], "answer": "all kinds of stamps", "audio": None},
  {"id": "bo04-q133", "number": 133, "type": "multiple_choice", "question": "What’s the … of Mexico City?- 12 million people.", "options": ["students", "languages", "populations", "seasons"], "answer": "populations", "audio": None},
  {"id": "bo04-q134", "number": 134, "type": "fill_blank", "question": "Why don’t we _ _ camping this weekend?", "answer": "go", "audio": None},
  {"id": "bo04-q135", "number": 135, "type": "fill_blank", "question": "Farmers are very hard-working. They work from morning _ _ _ _ night on their farms.", "answer": "till", "audio": None},
  {"id": "bo04-q136", "number": 136, "type": "multiple_choice", "question": "Susie is so …. She is always breaking things.", "options": ["careful", "carefully", "careless", "not careful"], "answer": "careless", "audio": None},
  {"id": "bo04-q137", "number": 137, "type": "multiple_choice", "question": "He was only thirteen, but he ate … his father did.", "options": ["as much as", "more that", "much than", "as much than"], "answer": "as much as", "audio": None},
  {"id": "bo04-q138", "number": 138, "type": "listening_multiple_choice", "question": "Listen and tick:", "options": ["Her birthday is on the third of May.", "Her birthday is on the fifth of July.", "Her birthday is on the fifth of March.", "Her birthday is on the fifth of May."], "answer": "Her birthday is on the fifth of May.", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302355911898601_Audio.mp3"},
  {"id": "bo04-q139", "number": 139, "type": "listening_fill", "question": "It is not fair to _ _ _ _ _ _ _ someone just because they don’t look like you want them to look.", "answer": "dislike", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241438408526435_Audio.mp3"},
  {"id": "bo04-q140", "number": 140, "type": "image_fill", "question": "The new born baby doesn’t have any _ _ _ _ _ at all.", "answer": "teeth", "audio": None},
  {"id": "bo04-q141", "number": 141, "type": "word_order", "question": "enough/ The shirt is not/ big/ to wear./ for her son/", "answer": "The shirt is not big enough for her son to wear.", "audio": None},
  {"id": "bo04-q142", "number": 142, "type": "fill_blank", "question": "Do you live near your parents? – No, I live _ _ _ from them.", "answer": "far", "audio": None},
  {"id": "bo04-q143", "number": 143, "type": "fill_blank", "question": "The past form of “have” is “_ _ _ ”.", "answer": "had", "audio": None},
  {"id": "bo04-q144", "number": 144, "type": "word_order", "question": "the morning?/ first/ you do/ in/ What do/", "answer": "What do you do first in the morning?", "audio": None},
  {"id": "bo04-q145", "number": 145, "type": "word_order", "question": "Let/ you/ lift the box./ help/ me/", "answer": "Let me help you lift the box.", "audio": None},
  {"id": "bo04-q146", "number": 146, "type": "fill_blank", "question": "Thanks for the present! – Do you like _ _ ?", "answer": "it", "audio": None},
  {"id": "bo04-q147", "number": 147, "type": "multiple_choice", "question": "They ... me this dress when they visited the town.", "options": ["buy", "will buy", "bought", "are buying"], "answer": "bought", "audio": None},
  {"id": "bo04-q148", "number": 148, "type": "fill_blank", "question": "These shops have goods _ _ _ sale at attractive price.", "answer": "for", "audio": None},
  {"id": "bo04-q149", "number": 149, "type": "fill_blank", "question": "A lot of work is being done _ _ students.", "answer": "by", "audio": None},
  {"id": "bo04-q150", "number": 150, "type": "fill_blank", "question": "This is the second time I ir_ _ _ _ the clothes for myself.", "answer": "oned", "audio": None},
  {"id": "bo04-q151", "number": 151, "type": "fill_blank", "question": "It’s very dark here. Turn on the light, _ _ _ _ _ _ .", "answer": "please", "audio": None},
  {"id": "bo04-q152", "number": 152, "type": "listening_fill", "question": "I sometimes _ _ _ _ _ _ _ what it would be like if I could fly like a bird.", "answer": "imagine", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/2/23/636865180927984727_Audio.mp3"},
  {"id": "bo04-q153", "number": 153, "type": "word_order", "question": "at break time./ friends is/ Talking with/ way of relaxing/ the most common/", "answer": "Talking with friends is the most common way of relaxing at break time.", "audio": None},
  {"id": "bo04-q154", "number": 154, "type": "fill_blank", "question": "There is no n_ _ _ to explain how that machine works. I have got the instruction book now.", "answer": "eed", "audio": None},
  {"id": "bo04-q155", "number": 155, "type": "word_order", "question": "Taylor/ last night./ lovely/ looked/ particularly/", "answer": "Taylor looked particularly lovely last night.", "audio": None},
  {"id": "bo04-q156", "number": 156, "type": "fill_blank", "question": "Mrs. Lien said you could reach her _ _ 8. 545 646.", "answer": "at", "audio": None},
  {"id": "bo04-q157", "number": 157, "type": "fill_blank", "question": "Could you _ _ _ _ me where the post office is?", "answer": "show", "audio": None},
  {"id": "bo04-q158", "number": 158, "type": "word_order", "question": "for a walk./ I ask her/ She often/ says no when/ to go out/", "answer": "She often says no when I ask her to go out for a walk.", "audio": None},
  {"id": "bo04-q159", "number": 159, "type": "image_fill", "question": "I learn how to play _ _ _ _ _ r at the school club.", "answer": "guita", "audio": None},
  {"id": "bo04-q160", "number": 160, "type": "multiple_choice", "question": "There is … yogurt in the fridge.", "options": ["a lots of", "few", "a little", "many"], "answer": "a little", "audio": None},
  {"id": "bo04-q161", "number": 161, "type": "word_order", "question": "in the/ are happy to/ The children/ play outside/ early morning./", "answer": "The children are happy to play outside in the early morning.", "audio": None},
  {"id": "bo04-q162", "number": 162, "type": "word_order", "question": "The hospital/ is on the/ Street./ Street and Pine/ corner of the Green/", "answer": "The hospital is on the corner of the Green Street and Pine Street.", "audio": None},
  {"id": "bo04-q163", "number": 163, "type": "multiple_choice", "question": "It is six thirty in the evening. Maria ... her homework.", "options": ["is doing", "does", "is / do", "will do"], "answer": "is doing", "audio": None},
  {"id": "bo04-q164", "number": 164, "type": "multiple_choice", "question": "… – That one.", "options": ["Which is your house?", "Where is your father?", "Is that your book?", "What is that book?"], "answer": "Which is your house?", "audio": None},
  {"id": "bo04-q165", "number": 165, "type": "fill_blank", "question": "Don’t worry about _ _ , Mom. I can take care of myself.", "answer": "me", "audio": None},
  {"id": "bo04-q166", "number": 166, "type": "word_order", "question": "has/ long/ Nam’s new friend/ hair./ black/", "answer": "Nam’s new friend has long black hair.", "audio": None},
  {"id": "bo04-q167", "number": 167, "type": "word_order", "question": "Did she/ how to/ new word?/ pronounce this/ teach you/", "answer": "Did she teach you how to pronounce this new word?", "audio": None},
  {"id": "bo04-q168", "number": 168, "type": "word_order", "question": "took part in/ and won the/ the competition/ championship./ His cousin/", "answer": "His cousin took part in the competition and won the championship.", "audio": None},
  {"id": "bo04-q169", "number": 169, "type": "fill_blank", "question": "How _ _ _ _ _ do you read an English magazine? – Every month.", "answer": "often", "audio": None},
  {"id": "bo04-q170", "number": 170, "type": "fill_blank", "question": "How _ _ _ _ are you going to stay here? – Just 2 days.", "answer": "long", "audio": None},
  {"id": "bo04-q171", "number": 171, "type": "multiple_choice", "question": "Let me ... your sick note!", "options": ["to see", "seeing", "see", "saw"], "answer": "see", "audio": None},
  {"id": "bo04-q172", "number": 172, "type": "fill_blank", "question": "You ought to learn how to _ _ _ _ this musical instrument.", "answer": "play", "audio": None},
  {"id": "bo04-q173", "number": 173, "type": "multiple_choice", "question": "Reading books … an important role in developing children’s creativity.", "options": ["playing", "play", "plays", "to play"], "answer": "plays", "audio": None},
  {"id": "bo04-q174", "number": 174, "type": "word_order", "question": "at her sister’s wedding/ wear/ a blue/ dress/ She is going to/", "answer": "She is going to wear a blue dress at her sister’s wedding", "audio": None},
  {"id": "bo04-q175", "number": 175, "type": "multiple_choice", "question": "...! It’s late.", "options": ["Going home now", "Go home now", "Going house now", "Go house now"], "answer": "Go home now", "audio": None},
  {"id": "bo04-q176", "number": 176, "type": "listening_multiple_choice", "question": "Where does Jane usually work? - ....", "options": ["in England", "in Holland", "in Poland", "in Ireland"], "answer": "in England", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302350408676935_Audio.mp3"},
  {"id": "bo04-q177", "number": 177, "type": "fill_blank", "question": "Every boys and girls j_ _ _ _ the activity enthusiastically.", "answer": "oins", "audio": None},
  {"id": "bo04-q178", "number": 178, "type": "word_order", "question": "to school?/ your sister/ ride bike/ Why/ doesn’t/", "answer": "Why doesn’t your sister ride bike to school?", "audio": None},
  {"id": "bo04-q179", "number": 179, "type": "listening_fill", "question": "Money doesn’t buy _ _ _ _ _ _ _ _ _ .", "answer": "happiness", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2017/3/3/636241442503847148_Audio.mp3"},
  {"id": "bo04-q180", "number": 180, "type": "image_fill", "question": "I need a new _ _ _ _ _ _ _ tor. Mine is broken for weeks.", "answer": "calcula", "audio": None},
  {"id": "bo04-q181", "number": 181, "type": "listening_multiple_choice", "question": "What do a lot of students do in the holiday? - ....", "options": ["Study", "Work", "Stay at home", "Have a trip"], "answer": "Work", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/12/635302346300565720_Audio.mp3"},
  {"id": "bo04-q182", "number": 182, "type": "pronunciation", "question": "Choose the word that has the underlined part pronounced differently:", "options": ["stomach", "orchestra", "catch", "school"], "answer": "catch", "audio": None},
  {"id": "bo04-q183", "number": 183, "type": "fill_blank", "question": "Every night I like to _ _ _ _ the internet for about an hour to find interesting information on the web!", "answer": "surf", "audio": None},
  {"id": "bo04-q184", "number": 184, "type": "word_order", "question": "Clara/ all her works./ the office after/ leaves/ finishing/", "answer": "Clara leaves the office after finishing all her works.", "audio": None},
  {"id": "bo04-q185", "number": 185, "type": "multiple_choice", "question": "I’m sick. – ... well soon.", "options": ["Take", "Have", "Get", "Be"], "answer": "Get", "audio": None},
  {"id": "bo04-q186", "number": 186, "type": "word_order", "question": "from Ho Chi Minh to/ does it take/ How long/ by plane?/ Noi Bai/", "answer": "How long does it take from Ho Chi Minh to Noi Bai by plane?", "audio": None},
  {"id": "bo04-q187", "number": 187, "type": "listening_multiple_choice", "question": "When is the beach busy? - ....", "options": ["From June to July", "From July to August", "From June to August", "From June to September"], "answer": "From June to August", "audio": "https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2014/3/13/635303162239250840_Audio.mp3"},
  {"id": "bo04-q188", "number": 188, "type": "fill_blank", "question": "The days are short and the _ _ _ _ _ _ are long in winter.", "answer": "nights", "audio": None},
  {"id": "bo04-q189", "number": 189, "type": "multiple_choice", "question": "She is often absent from school because of illness. It means she is ....", "options": ["strong", "unhealthy", "fit", "moderate"], "answer": "unhealthy", "audio": None},
  {"id": "bo04-q190", "number": 190, "type": "word_order", "question": "Mrs. Lan/ her/ called/ newspaper delivery./ about/", "answer": "Mrs. Lan called about her newspaper delivery.", "audio": None},
  {"id": "bo04-q191", "number": 191, "type": "word_order", "question": "meat./ much/ You shouldn’t/ eat/ too/", "answer": "You shouldn’t eat too much meat.", "audio": None},
  {"id": "bo04-q192", "number": 192, "type": "fill_blank", "question": "It’s a quarter _ _ one.", "answer": "to", "audio": None},
  {"id": "bo04-q193", "number": 193, "type": "multiple_choice", "question": "Is this your car? – No, it’s ....", "options": ["of Mr. Brown", "to Mr. Brown", "Mr. Brown’s", "Mr. Brown"], "answer": "Mr. Brown’s", "audio": None},
  {"id": "bo04-q194", "number": 194, "type": "fill_blank", "question": "CA_ CH", "answer": "T", "audio": None},
  {"id": "bo04-q195", "number": 195, "type": "fill_blank", "question": "It rained a _ _ _ in Chicago last week.", "answer": "lot", "audio": None},
  {"id": "bo04-q196", "number": 196, "type": "fill_blank", "question": "These symptoms will di_ _ _ _ ear after you take these pills", "answer": "sapp", "audio": None},
  {"id": "bo04-q197", "number": 197, "type": "image_fill", "question": "I loathe the sound of the d_ _ _ _ . It is so loud.", "answer": "rill", "audio": None},
  {"id": "bo04-q198", "number": 198, "type": "fill_blank", "question": "Many people have stopped smoking _ _ _ _ _ _ _ they are afraid that it may be harmful to their health.", "answer": "because", "audio": None},
  {"id": "bo04-q199", "number": 199, "type": "multiple_choice", "question": "The heavy rain prevented me … going camping.", "options": ["in", "about", "from", "with"], "answer": "from", "audio": None},
  {"id": "bo04-q200", "number": 200, "type": "word_order", "question": "be?/ will/ what/ I/ Mom,/", "answer": "Mom, what will I be?", "audio": None}
]

def get_bo04():
    questions = [normalize_question(q, 4) for q in raw_questions]
    return {
        "examId": "04",
        "setId": "bo04",
        "title": "IOE K7 2024-2025 - Đề số 04",
        "totalQuestions": len(questions),
        "questions": questions
    }
